### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by ThinGorilla** [atom/tabs#508] opened 2017-08-09 21:02 UTC
Atom is throwing a new error at me every minute. 

[Enter steps to reproduce:]

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At C:\Users\Kerrigan Marois\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2168

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:2168:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:2164:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:276:18)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:1423:18)
    at TextEditorComponent.didFocus (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:1447:35)
    at HTMLElement.addEventListener (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-element.js:36:67)
    at HTMLElement.PaneElement.activeItemChanged (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane-element.js:158:25)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.setActiveItem (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane.js:337:28)
    at Pane.module.exports.Pane.activateItemAtIndex (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane.js:475:25)
    at Pane.module.exports.Pane.activatePreviousItem (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane.js:440:27)
    at Pane.module.exports.Pane.removeItem (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane.js:630:22)
    at Pane.module.exports.Pane.destroyItem (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane.js:706:22)
    at TabBarView.module.exports.TabBarView.closeTab (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:340:32)
    at HTMLDivElement.TabView.didClickCloseIcon (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:228:25)
```

### Commands

```
     -3:30.3.0 core:paste (input.hidden-input)
 13x -3:10.4.0 core:backspace (input.hidden-input)
     -2:13.6.0 core:save (input.hidden-input)
     -2:07.8.0 open-in-browsers:Chrome (span.name.icon.icon-file-text)
     -1:14.3.0 command-palette:toggle (div.tool-panel.tree-view)
     -1:04.5.0 settings-view:check-for-package-updates (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-minify 0.8.0 
autoprefixer 3.7.1 
busy-signal 1.4.3 
emmet 2.4.3 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-csslint 1.3.4 
linter-ui-default 1.6.3 
minimap 4.29.3 
minimap-highlight-selected 4.6.1 
open-in-browsers 0.0.30 
todo-show 1.11.0 
```

**Comment by 50Wliu** [comment] 2017-08-10 01:39
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/atom#15168. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-10 01:39 UTC
