### ISSUE TITLE
disable closing tabs of deleted files by default

### ISSUE THREAD

**Issue by jonathankoren** [atom/tabs#322] opened 2016-05-07 04:59 UTC
Since https://github.com/atom/tabs/issues/160 when a file is deleted, Atom proactively closes the tab if that file is open, instead of simply staying open like every other editor.

This surprising and novel behavior can has resulted in result in lost work.

**Comment by lee-dohm** [comment] 2016-05-07 16:53
This is a duplicate of #306. Closing in favor of that Issue.

Atom only closes the tab if the file in memory is unchanged when the file on disk is deleted. If the file has been changed, then it is not closed to prevent any lost work.

**Closed by lee-dohm** 2016-05-07 16:53 UTC

**Comment by jonathankoren** [comment] 2016-05-07 21:50
@lee-dohm  The buffer itself is the work.
