### ISSUE TITLE
Uncaught Error: Pane has been destroyed (split pane with markdown preview item)

### ISSUE THREAD

**Issue by kuychaco** [atom/tabs#320] opened 2016-05-06 15:10 UTC
Repro steps: 

1. Open a markdown file
2. Toggle markdown preview (opens new pane to the right)
3. Close all tabs except markdown preview
4. Split pane and copy active item

Expected: pane is successfully split
Actual: pane does not split and Uncaught Error occurs

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Users/kuychaco/Downloads/Atom 4.app/Contents/Resources/app.asar/src/pane.js:804

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/Users/kuychaco/Downloads/Atom 4.app/Contents/Resources/app.asar/src/pane.js:804:15)
    at Pane.module.exports.Pane.split (/Users/kuychaco/Downloads/Atom 4.app/Contents/Resources/app.asar/src/pane.js:900:15)
    at Pane.module.exports.Pane.splitRight (/Users/kuychaco/Downloads/Atom 4.app/Contents/Resources/app.asar/src/pane.js:856:19)
    at atom-pane.commandRegistry.add.pane:split-right-and-copy-active-item (/Users/kuychaco/Downloads/Atom 4.app/Contents/Resources/app.asar/src/register-default-commands.js:247:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/kuychaco/Downloads/Atom 4.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/kuychaco/Downloads/Atom 4.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/kuychaco/Downloads/Atom 4.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/kuychaco/Downloads/Atom 4.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/kuychaco/Downloads/Atom 4.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/kuychaco/Downloads/Atom 4.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -3:41.3.0 command-palette:toggle (div.markdown-preview.native-key-bindings)
     -2:54.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:16.4.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:15 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:13.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:13.4.0 markdown-preview:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:33.4.0 command-palette:toggle (div.markdown-preview.native-key-bindings)
     -1:31 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:31 pane:split-up (div.markdown-preview.native-key-bindings)
     -1:22.7.0 core:close (atom-pane.pane.active)
     -1:17.7.0 command-palette:toggle (div.markdown-preview.native-key-bindings)
     -1:06.5.0 pane:split-right-and-copy-active-item (div.markdown-preview.native-key-bindings)
     -1:02.3.0 command-palette:toggle (div.markdown-preview.native-key-bindings)
     -0:56.8.0 pane:split-down-and-copy-active-item (div.markdown-preview.native-key-bindings)
     -0:44.7.0 command-palette:toggle (div.markdown-preview.native-key-bindings)
     -0:01.3.0 pane:split-right-and-copy-active-item (div.markdown-preview.native-key-bindings)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "vim-mode-plus",
      "vim-mode-plus-ex-mode",
      "git-plus",
      "symbol-gen",
      "ide-haskell",
      "terminal-plus",
      "minimap"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "confirmCheckoutHeadRevision": false,
    "fontFamily": "Fira Code",
    "fontSize": 15,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jasmine, v0.8.1
atom-pair, v2.0.10
autocomplete-emojis, v2.3.0
autocomplete-go, v1.0.8
builder-go, v1.0.0
environment, v1.2.0
floobits, v0.31.1
git, v0.0.0
github, v0.1.0
go-config, v1.1.4
go-get, v1.0.3
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
ide-haskell-cabal, v1.2.2
language-babel, v2.18.6
language-elm, v1.3.3
language-haskell, v1.7.13
linter, v1.11.4
merge-conflicts, v1.4.2
navigator-godef, v1.0.3
term3, v0.22.0
tester-go, v1.0.4

# Dev
git, v0.0.0
tree-view, v0.206.0
```

**Comment by 50Wliu** [comment] 2016-05-06 20:16
Duplicate of atom/atom#8652 (super-annoying how this error can be caused by so many different ways).

**Closed by 50Wliu** 2016-05-06 20:16 UTC
