### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '/home/martin/dev/git/scroll-pdf-cloud/src/main/front...

### ISSUE THREAD

**Issue by MartinMuzatko** [atom/tabs#267] opened 2016-02-25 15:10 UTC
[Enter steps to reproduce below:]

1. Have some Tabs loaded
2. Split View
3. Load some more Files
4. Close one Pane
5. Restart Atom
6. Have only one Pane but Files of both
7. Rightclick on Tabs -> Close Pane
8. Half of Tabs from earlier merged Pane are lost
9. Rightclick on Tab -> Close Tab

**Atom Version**: 1.5.3
**System**: Ubuntu 15.10
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.88.0

### Stack Trace

Uncaught Error: Adding a pane item with URI '/home/martin/dev/git/scroll-pdf-cloud/src/main/frontend/src/app/export/export.component.ts' that has already been destroyed

```
At /usr/share/atom/resources/app.asar/src/pane.js:342

Error: Adding a pane item with URI '/home/martin/dev/git/scroll-pdf-cloud/src/main/frontend/src/app/export/export.component.ts' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app.asar/src/pane.js:342:15)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:326:14)
    at atom-tabs.TabBarView.onMouseDown (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:670:19)
```

### Commands

```
     -1:37.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:36.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:15.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:03.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
 11x -1:00.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:50.6.0 core:move-left (atom-text-editor.editor.mini.is-focused)
  3x -0:49.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:42.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:42.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:29.1.0 project-find:show (atom-text-editor.editor.is-focused)
     -0:28 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:28 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -2:03.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:10.7.0 pane:close (div.close-icon)
     -0:10.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -0:02.2.0 pane:close (li.tab.sortable.right-clicked)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [],
    "projectHome": "/home/martin/dev/git/"
  },
  "tabs": {
    "enableVcsColoring": true,
    "usePreviewTabs": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
angular2-snippets, v0.3.0
atom-minify, v0.7.1
atom-typescript, v8.2.0
auto-reveal-active-file, v0.3.1
autocomplete-modules, v1.4.1
colorful-json, v1.0.0
emmet, v2.4.1
git-log, v0.4.1
highlight-selected, v0.11.2
language-log, v1.4.0
language-qml, v1.0.0
linter, v1.11.3
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
pigments, v0.24.1
pretty-json, v0.4.1
project-manager, v2.7.6
project-view, v0.5.0
resize-indent, v0.2.1
set-syntax, v0.3.0
seti-icons, v0.4.5
sublime-panes, v0.2.5
tab-title, v0.3.2
you-complete-me, v0.7.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-02-25 17:41
Looks similar to atom/atom#10903.

**Comment by MartinMuzatko** [comment] 2016-02-26 07:33
@50Wliu Yep! About the same with funny sideeffects.

**Comment by lee-dohm** [comment] 2016-02-26 20:20
Closing this as a duplicate of atom/atom#10903 then. Let me know if I jumped the gun :grinning:

**Closed by lee-dohm** 2016-02-26 20:20 UTC
Labels: uncaught-exception
