### ISSUE TITLE
Switching to a tab (clicking it) should give focus to the editor of that tab

### ISSUE THREAD

**Issue by Leonick** [atom/tabs#169] opened 2015-06-08 14:01 UTC
I've noticed that if you click a tab the editor of that tab does not gain focus, it should.

Example:
1. Select and copy something in tab 1
2. Select something else in tab 1
3. Open a new tab and past what you copied
4. Click tab 1 and press ctrl/cmd+c to copy, this should copy what was last, and still is, selected in that tab
5. Return to tab 2 and paste your clipboard, you'll find yourself pasting what was copied in step 1

This happens both between tabs in Atom or when going back and forth between applications (unless you alt+tab back), clicking the tabs seem to give focus to the rest of the UI, not the tab's editor which is expected and the behaviour found in other editors such as Notepad++.

**Comment by izuzak** [comment] 2015-06-08 14:09
Thanks for the report, @Leonick -- this looks like a duplicate of https://github.com/atom/atom/issues/6662, so I'm closing this in favor of that issue (since it's a bit older and there's already some discussion there).

**Closed by izuzak** 2015-06-08 14:09 UTC
