### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getUri' of undefined

### ISSUE THREAD

**Issue by LiJohnson** [atom/tabs#107] opened 2015-01-15 11:58 UTC
Uncaught TypeError: Cannot read property 'getUri' of undefined

**Atom Version**: 0.161.0
**System**: linux 3.13.0-24-generic
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.58.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:374

TypeError: Cannot read property 'getUri' of undefined
  at TabBarView.module.exports.TabBarView.onDragStart (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:374:22)
  at tabs-tab.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

/cc @atom/core

**Comment by 50Wliu** [comment] 2015-01-15 13:25
Hi, it looks like you're running a slightly outdated version of Atom.  Could you try updating to 0.172.0 and see if this still happens?  If it does, could you try running Atom in safe mode (`atom --safe`)?

**Comment by LiJohnson** [comment] 2015-01-16 12:49
:ok_hand:

**Comment by izuzak** [comment] 2015-06-10 12:48
Should have been fixed with https://github.com/atom/tabs/commit/fed5f4c41992a401f94f54dc57943f2c26dd3474 -- let us know if you can still reproduce. :bow:

**Closed by izuzak** 2015-06-10 12:48 UTC
