### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Dropbox\ngen-comp\main\cerebrum.cu' that has alrea...

### ISSUE THREAD

**Issue by lianguage** [atom/tabs#446] opened 2017-05-29 10:01 UTC
Steps to reproduce:
1. Opened up a project in one window, and in a second window open the same project.
2. Recover state of that project when prompted
3. Close a window and this exception is triggered.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.0

### Stack Trace

Uncaught Error: Adding a pane item with URI 'C:\Users\Liang\Dropbox\ngen-comp\main\cerebrum.cu' that has already been destroyed

```
At C:\Users\Liang\AppData\Local\atom\app-1.17.2\resources\app\src\pane.js:493

Error: Adding a pane item with URI 'C:\Users\Liang\Dropbox\ngen-comp\main\cerebrum.cu' that has already been destroyed
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:493:1)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:468:1)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/tabs/lib/tab-bar-view.js:701:1)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
```

### Non-Core Packages

```
minimap 4.28.2 
neon-syntax 0.3.7 
ubik-neon-syntax 1.9.0 
```

**Comment by rsese** [comment] 2017-05-29 18:45
Looks like a dupe of https://github.com/atom/tabs/issues/444 but you've got steps to reproduce which is great.  Can you copy over your details in that issue?

Also, can you also confirm this one bit for me?

> 1. Opened up a project in one window, and in a second window open the same project.
> 2. Recover state of that project when prompted

If I open a test project in one window and then open the same project in another window (with `File > Add Project Folder`), I don't get that prompt.  Is this behavior reproducible for you consistently?

**Closed by rsese** 2017-05-29 18:45 UTC
