### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by wwvuillemot** [atom/tabs#108] opened 2015-01-19 00:45 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.61.0

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:579

Error: Pane has been destroyed
  at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:579:15)
  at PaneContainer.module.exports.PaneContainer.activateNextPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:274:26)
  at Pane.module.exports.Pane.destroyed (/Applications/Atom.app/Contents/Resources/app/src/pane.js:600:24)
  at Pane.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/theorist/lib/model.js:218:14)
  at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app/src/pane.js:593:39)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:399:21)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:443:16)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -0:51.6 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:48.5 core:close (atom-text-editor.editor)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment] 2015-01-19 01:49
Hi @wwvuillemot, can you share some steps to reproduce this?  Also, if possible, can you please update to the latest Atom version (currently 0.174.0) and see if you can still reproduce this error?

**Comment by ijanos** [comment] 2015-03-02 12:30
Steps to reproduce with 0.184.0

1. start with no tabs open
2. open a markdown file
3. generate a markdown preview, this opens pane to the right
4. close the original tab, this will extend the right pane to take the whole window
5. right click on the preview tab and choose "Split Right"

**Comment by 50Wliu** [comment] 2015-03-02 13:07
Confirmed, thanks!

**Comment by JCCR** [comment] 2015-06-23 03:38
It appears to be because the pane item it tries to copy (markdown preview view in this case) has no "copy" method implemented.

**Comment by Arcanemagus** [comment] 2016-03-04 19:59
For another set of steps to reproduce in v1.6.0-beta7:

1. Open a file in preview mode (single click)
2. Split a file right (opens in "regular" mode)
3. Single click on a third file, this should open in preview mode in the right pane
4. Attempt to drag the newest preview mode tab over to the left side

**Comment by 50Wliu** [comment] 2016-03-04 20:27
In an attempt to keep all of these "Pane has been destroyed" issues separate from one another, I'm going to close this one.

@Arcanemagus Please file a new bug.
@ijanos @JCCR feel free to subscribe to atom/atom#8652 for updates.
@wwvuillemot Your issue might best be described by atom/atom#10903.

**Closed by 50Wliu** 2016-03-04 20:27 UTC
Labels: bug, uncaught-exception
