### ISSUE TITLE
Split panes are always empty

### ISSUE THREAD

**Issue by ricardograca** [atom/tabs#307] opened 2016-04-18 11:14 UTC
When using any of the split pane commands (up, down, left, right) on an open file, the result is always an empty pane. I noticed this behavior in version 1.6.0, upgraded to 1.7.1 and it's still a problem.

Things that **don't** fix this issue:
- Starting Atom in safe mode
- Deleting the `~/.atom` directory and reloading Atom
- Using another user session

After the empty pane is open I can drag already opened tabs onto it, but they will be removed from the original pane obviously. If I then close the file tab that was dragged into the previously empty pane, the pane is automatically closed as expected. Opening files from the tree-view while the empty pane is selected will open those files correctly on the previously empty pane.

So, the only thing that seems to be missing is that using the split pane commands by right clicking on an open file in the editor view (or using the window menu) doesn't result in the file being open on the newly created pane.

Here's what happens:

![gifrecord_2016-04-18_120508](https://cloud.githubusercontent.com/assets/1457035/14602292/0e42c7c8-055f-11e6-945c-6421e79253bd.gif)

Ubuntu 15.04, Atom 1.7.1.

**Comment by 50Wliu** [comment] 2016-04-18 12:26
This is a duplicate of atom/atom#11381 - feel free to subscribe there for updates.  In the meantime splitting panes from the tab menu and not the editor should copy the active tab over.

**Closed by 50Wliu** 2016-04-18 12:26 UTC
