### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '/Applications/MAMP/htdocs/medikaria-app/resources/vi...

### ISSUE THREAD

**Issue by rbarrientos182** [atom/tabs#444] opened 2017-05-24 15:40 UTC
Steps to reproduce by @Ben3eeE https://github.com/atom/tabs/issues/444#issuecomment-321207395

I was able to reproduce this exception by clicking the scroll wheel and left mouse button at the same time on a tab. Clicking the scroll wheel closes the tab and left mouse button activates the tab. I found it easier to reproduce on larger files and I used `AtomSetup.exe` when reproducing. It took me a few tries to reproduce because it requires good timing.

https://github.com/atom/tabs/commit/1849b1181eac56be2b7b62bb15bb2d914ba83152?

![adding tab closed](https://user-images.githubusercontent.com/1058982/29111685-8a13756e-7ceb-11e7-9969-329e6f92dd79.gif)

If you do the same steps on an `image-view` tab another exception is thrown and the `image-view` does not close.

![adding tab image](https://user-images.githubusercontent.com/1058982/29114383-677becbc-7cf4-11e7-93c4-7b6e9b154bdd.gif)

---

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.0

### Stack Trace

Uncaught Error: Adding a pane item with URI '/Applications/MAMP/htdocs/medikaria-app/resources/views/welcome.blade.php' that has already been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:493

Error: Adding a pane item with URI '/Applications/MAMP/htdocs/medikaria-app/resources/views/welcome.blade.php' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:493:1)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:468:1)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:701:1)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -1:13.9.0 application:reopen-project (input.hidden-input)
```

### Non-Core Packages

```
atom-django 0.3.2 
django-templates 0.5.0 
language-blade 0.29.0 
laravel 0.7.1 
terminal-plus 0.14.5 
```

**Comment by rsese** [comment] 2017-05-24 20:37
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by daveomcd** [comment] 2017-06-23 14:00
What lead me to this error seemed to be my VM Guest being overall unresponsive.  Then I clicked the "X" to close out a tab in Atom, and when it didn't close I clicked it again (perhaps 2 or 3 more times).  When the Guest finally responded it executed many of those clicking functions it appeared - but some must have come after the tab had been closed to some extent I'm guessing.  Also possibly related, it seems the system slow down might've been due to a web page that was opened in Firefox.  I received a pop up saying that a jquery.min.css had also had an issue from that page (or possibly it was notifying me about it from atom's issue).  Sorry I didn't think about grabbing that error until after I closed out of it.

**Comment by Ben3eeE** [comment] 2017-08-09 09:43
@rsese @jasonrudolph I was able to reproduce this exception by clicking the scroll wheel and left mouse button at the same time on a tab. Clicking the scroll wheel closes the tab and left mouse button activates the tab. I found it easier to reproduce on larger files and I used `AtomSetup.exe` when reproducing. It took me a few tries to reproduce because it requires good timing.

https://github.com/atom/tabs/commit/1849b1181eac56be2b7b62bb15bb2d914ba83152?

![adding tab closed](https://user-images.githubusercontent.com/1058982/29111685-8a13756e-7ceb-11e7-9969-329e6f92dd79.gif)

If you do the same steps on an `image-view` tab another exception is thrown and the `image-view` does not close.

![adding tab image](https://user-images.githubusercontent.com/1058982/29114383-677becbc-7cf4-11e7-93c4-7b6e9b154bdd.gif)

Let me know if you need more information or help reproducing.

**Atom**: 1.19.0-beta7 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.61.2


### Stack Trace

Uncaught Error: Emitter has been disposed

```
At C:\Users\lineri\AppData\Local\atom\app-1.19.0-beta7\resources\app\node_modules\event-kit\lib\emitter.js:77

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/node_modules/event-kit/lib/emitter.js:77:21)
    at ImageEditorView.onDidLoad (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/node_modules/image-view/lib/image-editor-view.js:154:33)
    at ImageEditorStatusView.updateImageSize (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/node_modules/image-view/lib/image-editor-status-view.js:88:58)
    at ~/AppData/Local/atom/app-1.19.0-beta7/resources/app/node_modules/image-view/lib/image-editor-status-view.js:46:19
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/workspace.js:493:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/pane-container.js:284:26)
    at Pane.module.exports.Pane.setActiveItem (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/pane.js:339:22)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/src/pane.js:492:27)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.19.0-beta7/resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment] 2017-08-09 13:24
Confirmed with @Ben3eeE's steps.

**Comment by maxbrunsfeld** [comment] 2018-11-15 00:17
I'm going to close this out because:

* We haven't had any reports since November 2017
* @Ben3eeE recently found that it did not reproduce using the old steps
* The code that was causing the error was rewritten in #515

**Closed by maxbrunsfeld** 2018-11-15 00:17 UTC
Labels: bug, d ⬇️, i ⬆️, triaged, uncaught-exception, v ⬆️
