### ISSUE TITLE
Don't immediately resize tabs on close

### ISSUE THREAD

**Issue by ethanclevenger91** [atom/tabs#255] opened 2016-02-02 20:04 UTC
In Chrome, if you close a tab, the other tabs don't resize until you mouse out of the tab area plus a short timeout. This is great, because you can close several tabs in quick succession without having to move the mouse. 

With Atom, the tabs resize immediately if need be, which moved the close button, so you have to mouse back to it. Would be nice the Chrome-like behavior in Atom.

**Comment by 50Wliu** [comment] 2016-02-02 20:31
Hi @ethanclevenger91, this seems to be a duplicate of #129 - feel free to subscribe there for updates.  Thanks!

**Closed by 50Wliu** 2016-02-02 20:31 UTC

**Comment by ethanclevenger91** [comment] 2016-02-02 20:39
Ah, I looked and everything. Thanks!
