### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Workspaces/Angular IDE 2017 CI/yih-ui/src/app/yih/...

### ISSUE THREAD

**Issue by chaitaya** [atom/tabs#472] opened 2017-07-01 07:10 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI '/Users/macbook/Workspaces/Angular IDE 2017 CI/yih-ui/src/app/yih/common/models/masterload/sourcing-rules/sourcing-rule-header-object.ts' that has already been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:493

Error: Adding a pane item with URI '/Users/macbook/Workspaces/Angular IDE 2017 CI/yih-ui/src/app/yih/common/models/masterload/sourcing-rules/sourcing-rule-header-object.ts' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:493:21)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:468:20)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -3:56.8.0 core:save (input.hidden-input)
 38x -3:53.9.0 core:undo (input.hidden-input)
     -3:49.9.0 core:save (input.hidden-input)
     -3:33 editor:select-to-first-character-of-line (input.hidden-input)
     -3:32.8.0 core:backspace (input.hidden-input)
     -3:32.1.0 core:move-down (input.hidden-input)
 17x -3:29.9.0 core:save (button.btn.btn-all.disabled)
     -2:54.3.0 core:undo (input.hidden-input)
  4x -2:40.2.0 core:save (input.hidden-input)
 49x -2:21.5.0 core:move-down (input.hidden-input)
 58x -2:16.4.0 core:move-up (input.hidden-input)
     -1:58 core:confirm (input.hidden-input)
     -1:54.3.0 core:save (button.btn.btn-next.disabled)
     -1:38 core:move-to-bottom (input.hidden-input)
  2x -1:36.2.0 core:backspace (input.hidden-input)
     -1:35.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.4 
busy-signal 1.4.3 
eclipse-keybindings 0.9.0 
intentions 1.1.2 
language-typescript-grammars-only 1.6.0 
linter 2.2.0 
linter-ui-default 1.6.2 
platformio-ide-terminal 2.5.1 
typescript-modules-helper 0.8.0 
```

**Comment by rsese** [comment] 2017-07-03 21:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates - if you have consistent steps to reproduce, please let us know in the issue!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-03 21:56 UTC
