### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Documents/rails_projects/bmoretasty/test/controlle...

### ISSUE THREAD

**Issue by daveomcd** [atom/tabs#462] opened 2017-06-22 22:59 UTC
[Enter steps to reproduce:]

1. Clicked the "X" for a tab
2. System seemed to be unresponsive, so I clicked it again
3. Then the box showed up in Atom that recommended me writing up this ticket

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI '/home/daveomcd/Documents/rails_projects/bmoretasty/test/controllers/dishes_controller_test.rb' that has already been destroyed

```
At /usr/share/atom/resources/app/src/pane.js:493

Error: Adding a pane item with URI '/home/daveomcd/Documents/rails_projects/bmoretasty/test/controllers/dishes_controller_test.rb' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:493:21)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:468:20)
    at Immediate.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -9:11.6.0 editor:newline (input.hidden-input)
     -9:09.7.0 core:save (input.hidden-input)
  2x -8:00.3.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -7:59.3.0 core:backspace (input.hidden-input)
     -7:57.9.0 core:save (input.hidden-input)
  5x -7:49.8.0 core:select-up (input.hidden-input)
  2x -7:47.6.0 core:backspace (input.hidden-input)
  2x -7:45.6.0 core:save (input.hidden-input)
  2x -7:41.9.0 core:undo (input.hidden-input)
  2x -7:39.9.0 core:backspace (input.hidden-input)
     -7:38.4.0 core:save (input.hidden-input)
  2x -7:16.8.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -7:16 core:backspace (input.hidden-input)
  3x -7:15.2.0 core:save (input.hidden-input)
     -0:54.2.0 editor:newline (input.hidden-input)
     -0:50.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by daveomcd** [comment] 2017-06-22 23:01
Seems like a duplicate from viewing other issues.  I'm sort-of new to reporting issues on Github, if there is a way to merge mine with other please let me know. Thanks!

**Comment by rsese** [comment] 2017-06-23 04:58
Yep looks like a dupe of https://github.com/atom/tabs/issues/444, thanks for scanning through the existing issues!

There's no issue merging functionality on GitHub so we just close duplicates and label them as a dupe.  If you'd like, you can subscribe to https://github.com/atom/tabs/issues/444 for updates.

If you can let us know in that issue if the error is reproducible and if it's reproducible in safe mode (`atom --safe`), that would be helpful too :v:

**Closed by rsese** 2017-06-23 04:58 UTC
