### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Desktop\Practice\css\style.css' that has already b...

### ISSUE THREAD

**Issue by cheemasinghk** [atom/tabs#516] opened 2017-08-21 10:17 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI 'C:\Users\keerat\Desktop\Practice\css\style.css' that has already been destroyed

```
At C:\Users\keerat\AppData\Local\atom\app-1.19.2\resources\app\src\pane.js:514

Error: Adding a pane item with URI 'C:\Users\keerat\Desktop\Practice\css\style.css' that has already been destroyed
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.19.2/resources/app/src/pane.js:514:21)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.19.2/resources/app/src/pane.js:489:20)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -0:58.8.0 core:save (ul.list-inline.tab-bar.inset-panel)
     -0:01.0 core:focus-next (a.btn-issue.btn.btn-error.opening)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-bootstrap4 1.4.0 
auto-detect-indentation 1.3.0 
emmet 2.4.3 
```

**Comment by 50Wliu** [comment] 2017-08-21 22:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #444. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-21 22:56 UTC
