### ISSUE TITLE
Closing multiple tabs with unsaved changes should focus on each tab one by one

### ISSUE THREAD

**Issue by dbachko** [atom/tabs#321] opened 2016-05-06 20:59 UTC
When you close tabs with this commands: 'tabs:close-other-tabs', 'tabs:close-tabs-to-right', 'tabs:close-tabs-to-left', 'tabs:close-all-tabs' and some of them have unsaved changes we can see the dialog "... has changes, do you want to save them?". Could be useful to focus on the current closing tab to see its content.

**Comment by Yajo** [comment] 2016-05-30 14:02
I think it's more useful to have a single dialog. If you have 10 tabs, pressing 10 times to a button that changes its position is annoying.

**Comment by AbdelrahmanHafez** [comment] 2016-09-11 09:21
Why not both? Save all, Save current tab only, cancel

**Comment by Ben3eeE** [comment] 2016-10-09 18:32
This is a duplicate of https://github.com/atom/atom/issues/6070. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-09 18:32 UTC
