### ISSUE TITLE
Uncaught Error: Adding a pane item with URI 'bundle.js'

### ISSUE THREAD

**Issue by Mottie** [atom/tabs#511] opened 2017-08-12 23:08 UTC
[Enter steps to reproduce:]

1. Open a very large file (e.g. a `bundle.js` from browserify).
2. Close the editor.
3. Reopen the editor, but click on "x" of the `bundle.js` tab to close it (because it is laggy).

\*Note\* I was *not* able to reproduce this issue every time... it must have been a fluke.

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI 'bundle.js' that has already been destroyed

```
At C:\Users\zzz\AppData\Local\atom\app-1.19.0\resources\app\src\pane.js:514

Error: Adding a pane item with URI 'bundle.js' that has already been destroyed
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane.js:514:21)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane.js:489:20)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -0:39.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:31.3.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-name-that-color 0.2.0 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
color-picker 2.2.5 
editorconfig 2.2.2 
figlet 0.5.4 
file-icons 2.1.10 
intentions 1.1.5 
language-matlab-octave 0.1.2 
language-rust 0.4.12 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-rust 0.8.0 
linter-stylelint 4.0.1 
linter-ui-default 1.6.4 
linter-xo 0.23.1 
minimap 4.29.6 
open-conemu-here 0.5.0 
open-in-browser 0.5.2 
pigments 0.40.2 
react 0.16.2 
tab-close 2.1.0 
tabs-to-spaces 1.0.3 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
troll-stopper 1.0.0 
```

**Comment by Ben3eeE** [comment] 2017-08-14 11:58
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-14 11:58 UTC
Labels: duplicate
