### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by sahina** [atom/tabs#234] opened 2015-11-12 14:10 UTC
One set of steps to reproduce from https://github.com/atom/tabs/issues/234#issuecomment-306439035:

1. Start Atom with some project `atom .`
2. Right click `Project` above the tree view
3. Choose one of the `Split` options, e.g. `Split Down`

At this point you get the error and the project in the tree view disappears - you need to clear saved state to use the project again.

---

1. Updated packages and opened my latest project file .jsx.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.84.0
### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
  at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11:15)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:374:25)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:359:28
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:339:20)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:310:14)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -0:09.7.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false
  },
  "tabs": {
    "usePreviewTabs": true
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
Stylus, v1.2.1
angularjs, v0.3.3
atom-typescript, v7.8.0
coffee-compile, v0.19.2
color-picker, v2.0.13
emmet, v2.3.14
language-babel, v2.4.1
language-ejs, v0.2.0
language-jade, v0.6.2
language-rust, v0.4.5
less-autocompile, v1.0.0
linter, v1.10.0
linter-eslint, v4.0.0
linter-less, v2.2.0
linter-rust, v0.2.10
linter-stylint, v2.0.1
react, v0.12.10

# Dev
No dev packages
```

**Comment by breiter** [comment] 2015-11-24 04:58
## Reproduce
I have preview tabs on and had a buffer open that I told Atom not to save before it restarted to apply a version upgrade.

**Comment by adambuczynski** [comment] 2015-12-31 23:55
Got this error when I re-opened a project window (through project-manager) that had crashed.

**Comment by dgm** [comment] 2016-01-12 22:42
I get this error repeatedly, usually after doing a search in files and the closing the results with cmd-w.  I also noticed once that the tab order was wonky - alt-2 and alt-3 went to the wrong tabs, like they had gotten reversed.

**Comment by magic890** [comment] 2016-02-04 11:03
**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.88.0


### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:374:25)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:359:28
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:344:20)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:315:14)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:670:19)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-log",
      "console-log",
      "language-log"
    ]
  },
  "tabs": {
    "enableVcsColoring": true,
    "usePreviewTabs": true
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.2.0
autoclose-html, v0.20.0
file-icons, v1.6.14
language-hocon, v1.1.0
language-latex, v0.6.1
language-scala, v1.1.6
linter, v1.11.3
minimap, v4.19.0
pigments, v0.23.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2017-05-03 20:30
[Enter steps to reproduce:]

1. Open Atom in safe mode
2. Open the About tab
3. Right click the tab -> Split right

**Atom**: 1.17.0-beta4 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.105.4


### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At C:\Users\Landon Abney\AppData\Local\atom\app-1.17.0-beta4\resources\app\src\item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/item-registry.js:11:1)
    at PaneContainer.didAddPaneItem (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/pane-container.js:265:1)
    at PaneContainer.didAddPane (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/pane-container.js:238:1)
    at Pane.module.exports.Pane.setContainer (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/pane.js:149:1)
    at PaneAxis.module.exports.PaneAxis.addChild (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/pane-axis.js:154:1)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/pane-axis.js:225:1)
    at Pane.module.exports.Pane.split (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/pane.js:968:1)
    at Pane.module.exports.Pane.splitRight (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/pane.js:928:1)
    at TabBarView.module.exports.TabBarView.splitTab (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/node_modules/tabs/lib/tab-bar-view.js:378:1)
    at Object.TabBarView.addElementCommands.tabs:split-right (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/node_modules/tabs/lib/tab-bar-view.js:136:1)
    at HTMLUListElement.commandsWithPropagationStopped.(anonymous function) (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/node_modules/tabs/lib/tab-bar-view.js:82:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/atom-environment.js:1292:1)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -0:47.6.0 tabs:split-right (div.title)
```

### Non-Core Packages

```

```

Note: Also tested with Atom v1.16.0 x64 with the same result.

**Comment by rsese** [comment] 2017-05-05 23:09
I can reproduce with @Arcanemagus steps :+1:

**Comment by 50Wliu** [comment] 2017-05-06 03:11
@Arcanemagus that bug already has an issue at atom/about#30.

**Comment by Arcanemagus** [comment] 2017-05-07 00:23
Reported it here since that's where Atom said it was thrown from, from the previous reports in this thread it seems like there are many different ways this can be triggered I just reported one way to reliably reproduce it 😉.

**Comment by alice-em** [comment] 2017-05-23 18:21
```
Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app/src/item-registry.js:11:1)
    at PaneContainer.didAddPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:265:1)
    at PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:238:1)
    at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app/src/pane.js:149:1)
    at PaneAxis.module.exports.PaneAxis.addChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:154:1)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:225:1)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:968:1)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app/src/pane.js:928:1)
    at TabBarView.module.exports.TabBarView.splitTab (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:378:1)
    at Object.TabBarView.addElementCommands.tabs:split-right (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:136:1)
    at HTMLUListElement.commandsWithPropagationStopped.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:82:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1292:1)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

I got this today on `El Capitan` OSX, by accidentally double clicking on my project's tab in the left side bar.

**Comment by luismqueral** [comment] 2017-05-26 01:58
+1 I got this today, thanks for the succinct reproduction steps @Arcanemagus 😎

**Comment by tizmagik** [comment] 2017-05-30 18:32
I just got this today as well. Is there a known workaround?

**Comment by aeolingamenfel** [comment] 2017-06-05 20:26
Also got this. Seems to persist between uninstalling Atom and reinstalling Atom.

**Comment by aeolingamenfel** [comment] 2017-06-05 20:27
Actually, running the following will fix the issue (but will obviously clear anything Atom was storing about your project):

```bash
atom --clear-window-state
```

**Comment by Neosublimation** [comment] 2017-06-06 09:58
Actually this is very easy to reproduce. Just split (tested with down, may work with other directions as well) the *Projects* tab.

**Comment by albertbuchard** [comment] 2017-06-24 19:17
persists whatever I do

**Comment by MaxShcherbakov** [comment] 2017-09-01 07:18
I did split tree-view and it's gone. Same error in console. I did delete .atom folder with all config, packages e.t.c. But the problem remained. Please help! What do i need to do to return my tree-view back?

**Closed** 2017-09-23 23:45 UTC
Labels: bug, triaged, uncaught-exception
