### ISSUE TITLE
Error: Editor is not responding

### ISSUE THREAD

**Issue by RefactorMan** [atom/tabs#323] opened 2016-05-08 09:30 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom rises an error dialog.

### Steps to Reproduce

1. open some file or tab.
2. right click on the new tab.

![image](https://cloud.githubusercontent.com/assets/5955905/15097020/8c58ec60-1517-11e6-9e87-82c05a3c9a70.png)

3. wait about 30 seconds
4. the error dialog shows up. (dialog in picture)
    * if you click on "Keep Waiting", the dialog will close.
    * if you press on the "close" button , Atom will CRASH.

![image](https://cloud.githubusercontent.com/assets/5955905/15096958/a7de6ec6-1515-11e6-8b3f-6f7e518d3b26.png)

**Expected behavior:** 
should not crash or raise any error dialog after right click on any tab.

**Actual behavior:** 
rise an error dialog\message when you right click the mouse and wait for about 30 seconds.

### Versions
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 1.9.5.msysgit.0
visual studio 2013

windows 10

**Comment by Ben3eeE** [comment] 2016-05-10 06:43
This is not limited to the tabs package. I can reproduce it by right clicking anywhere where a context menu is displayed. Atom doesn't seem to update when the context menu is shown.

The close button doesn't crash atom for me, it does a force close. But the button text/placement for this dialog is really weird. Because now if you close this dialog with the X or by pressing escape atom will force close. Also a button with the text Close normally just closes the dialog on Windows?

Windows 7 Atom 1.7.3 in safe mode.

**Comment by Ben3eeE** [comment] 2016-05-19 12:27
@lee-dohm Also a duplicate of https://github.com/atom/atom/issues/2991? Seems like the wrong repository at the very least.

**Comment by lee-dohm** [comment] 2016-05-19 19:42
@Ben3eeE I believe the error that they are trying to point out is that if you leave the context menu open, eventually the editor says it is not responding. Atom shouldn't do this.

@damieng or @amytruong Can you reproduce this behavior?

**Comment by Ben3eeE** [comment] 2016-05-19 20:22
What I meant is that it is similar to that issue in that it (And others mentioned in it) discusses Atom not updating with the context menu displayed, maybe not a direct duplicate but similar.
Atom stops updating completely for me when opening the context menu from anywhere and if you wait long enough (30 seconds) this keep waiting dialog appears. I was able to reproduce this in Atom 1.9.0-dev-f40b1cd on Windows 10.

**Comment by damieng** [comment] 2016-05-19 21:36
I do see the Keep Waiting message if I right click for 30 seconds but if I click Keep Waiting it comes back to life.

Given the rest of Atom doesn't update what I suspect is happening here is that we are somehow locking the UI with the context menu and Windows is proactively spotting that and giving it 30 seconds to come back.

**Comment by damieng** [comment] 2016-05-19 21:38
I also see this on non-tabs context menus - I think this is an Atom bug rather than a tabs bug.

**Comment by amytruong** [comment] 2016-05-20 00:26
I tried and I do get the Keep Waiting message as well.

**Comment by 50Wliu** [comment] 2016-06-04 20:13
Now that there's an issue open in Atom core, I'm going to close this in favor of atom/atom#11901.

**Closed by 50Wliu** 2016-06-04 20:13 UTC
Labels: bug
