### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Development/git/buildroot/arch/Config.in' that has...

### ISSUE THREAD

**Issue by joerg-krause** [atom/tabs#502] opened 2017-07-28 07:53 UTC
[Enter steps to reproduce:]

1. Opened Atom
2. Closed opened tabs using STRG+W immediately as Atom has opened

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: linux 4.9.37-1-lts
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI '/home/joerg/Development/git/buildroot/arch/Config.in' that has already been destroyed

```
At /usr/share/atom/resources/app/src/pane.js:493

Error: Adding a pane item with URI '/home/joerg/Development/git/buildroot/arch/Config.in' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:493:21)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:468:20)
    at Immediate.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
  2x -0:03.1.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -0:02.3.0 intentions:highlight (input.hidden-input)
  2x -0:02.3.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
busy-signal 1.4.3 
git-diff-details 1.4.0 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.9.3 
git-status 0.3.4 
intentions 1.1.5 
language-autotools 2.0.1 
language-cmake 0.3.0 
language-lua 0.9.11 
language-rust 0.4.11 
linter 2.2.0 
linter-eslint 8.2.1 
linter-jshint 3.1.5 
linter-lua 1.0.4 
linter-rust 0.8.0 
linter-ui-default 1.6.3 
merge-conflicts 1.4.5 
rust-api-docs-helper 0.5.1 
split-diff 1.4.3 
```

**Comment by rsese** [comment] 2017-07-31 07:10
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates - if you can reproduce with your repro steps in safe mode (`atom --safe`), please let us know in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-31 07:10 UTC
