### ISSUE TITLE
Uncaught Error: Adding a pane item with URI 'D:/ISG\isg_suite_ustore\src\containers\Workspace\Wor...

### ISSUE THREAD

**Issue by wangkang666** [atom/tabs#491] opened 2017-07-18 02:13 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI 'D:\ISG\isg_suite_ustore\src\containers\Workspace\WorkspaceView.js' that has already been destroyed

```
At C:\Users\thinkpad\AppData\Local\atom\app-1.18.0\resources\app\src\pane.js:493

Error: Adding a pane item with URI 'D:\ISG\isg_suite_ustore\src\containers\Workspace\WorkspaceView.js' that has already been destroyed
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:493:21)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:468:20)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -0:12.8.0 intentions:highlight (input.hidden-input)
     -0:12.6.0 core:undo (input.hidden-input)
     -0:10.8.0 intentions:highlight (input.hidden-input)
     -0:10.7.0 core:undo (input.hidden-input)
     -0:10.2.0 intentions:highlight (input.hidden-input)
  2x -0:10 core:undo (input.hidden-input)
     -0:08.8.0 intentions:highlight (input.hidden-input)
  3x -0:08.7.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
git-control 0.9.0 
minimap-linter 2.0.0 
minimap-linter 2.0.0 
react 0.16.2 
atom-simplified-chinese-menu 0.6.5 
autoclose-html 0.24.0 
autocomplete-paths 1.0.5 
busy-signal 1.4.1 
css-snippets 1.1.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-type-icons 1.3.4 
git-plus 7.8.0 
highlight-selected 0.13.1 
hyperclick 0.1.1 
intentions 1.1.2 
jquery-snippets 11.0.0 
language-babel 2.66.0 
language-javascript-jsx 0.3.7 
language-vue-component 0.5.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.2 
minimap 4.28.2 
nativebase-snippets-atom 2.0.2 
path-hyperclick 0.3.0 
tree-view-finder 0.2.1 
```

**Comment by rsese** [comment] 2017-07-19 17:35
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates - if you have consistent steps to reproduce in safe mode, please let us know in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-19 17:35 UTC
