### ISSUE TITLE
The focus changed to tree view when switching between tab using ctrl-page-up / ctrl-page-down

### ISSUE THREAD

**Issue by cytsunny** [atom/tabs#389] opened 2016-10-19 07:39 UTC
### Description

I updated atom manually yesterday. The problem happens after update and sorry I forgot what was the version before update. For current version, please check the version section below.

Before update when I switching between tabs using ctrl-page-up / ctr-page-down, the focus remains inside the content section so that I can navigate inside the content using arrow keys and edit immediately. 

After update, the focus changed to tree-view windows when I do the same action and using arrow keys just navigate in the tree view. I would now need a mouse click to re-focus on the content. That defeat the purpose of the hotkey - why don't I just click the tab if I need a mouse click to re-focus?

Besides update, I have recently turn off the option "Hide VCS ignored files" in the core tree-view package. Not sure if that's related. No change in all other packages other than this one.

### Steps to Reproduce

1. File>Open folder so that there is a tree-view display 
2. Open a few tabs
3. Give focus to content section
4. Navigate between tab using ctrl-page-up / ctrl-page-down hotkeys

**Expected behavior:** Focus stay in content section

**Actual behavior:** Focus switched to tree view

### Versions
**atom --version**
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**apm --version**
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.8.4.windows.1
visual studio

**ver**
Microsoft Windows [Version 10.0.14393]

**Comment by Ben3eeE** [comment] 2016-10-19 08:07
Because you mention changing `tree-view` settings in addition to upgrading Atom I am confident that this is a duplicate of https://github.com/atom/tree-view/issues/858. As a workaround you can disable the `tree-view` setting `Focus on Reveal`. Feel free to subscribe to that issue for updates.

**Closed by Ben3eeE** 2016-10-19 08:07 UTC
