### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/www\Gacheru\app\Exceptions\Handler.php' that has a...

### ISSUE THREAD

**Issue by MartinGacheru** [atom/tabs#513] opened 2017-08-14 11:29 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0-beta1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI 'C:\Users\Martin\www\Gacheru\app\Exceptions\Handler.php' that has already been destroyed

```
At C:\ProgramData\Martin\atom\app-1.20.0-beta1\resources\app\src\pane.js:514

Error: Adding a pane item with URI 'C:\Users\Martin\www\Gacheru\app\Exceptions\Handler.php' that has already been destroyed
    at Pane.module.exports.Pane.addItem (C:/ProgramData/Martin/atom/app-1.20.0-beta1/resources/app/src/pane.js:514:21)
    at Pane.module.exports.Pane.activateItem (C:/ProgramData/Martin/atom/app-1.20.0-beta1/resources/app/src/pane.js:489:20)
    at Immediate.<anonymous> (C:/ProgramData/Martin/atom/app-1.20.0-beta1/resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-live-server 2.1.2 
```

**Comment by Ben3eeE** [comment] 2017-08-14 11:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-14 11:56 UTC
Labels: duplicate
