### ISSUE TITLE
Editor not focused when switching tabs

### ISSUE THREAD

**Issue by Eschon** [atom/tabs#135] opened 2015-05-08 10:33 UTC
When I switch tabs the editor doesn't get focus. According to #30 this should have been fixed already but it doesn't work for me.

OS: OS X 10.10.3
Atom Version: 0.198.0
Tabs Version: 0.68.0

**Comment by mnquintana** [comment] 2015-05-08 11:48
Duplicate of https://github.com/atom/atom/issues/6662 - please subscribe there for updates.

**Closed by mnquintana** 2015-05-08 11:48 UTC

**Comment by kaisellgren** [comment] 2016-06-26 11:52
I had this same problem and it turned out it was the Settings -> Tree View -> Focus On Reveal option. Turning it off will keep the focus on the editor while switching tabs.
