### ISSUE TITLE
Tab Scrolling gives two blank options

### ISSUE THREAD

**Issue by drewmnoel** [atom/tabs#398] opened 2016-11-11 20:01 UTC
When exploring the settings, I noticed there's three options for scrolling. Two of them are blank: ![]()
![2016-11-11-145821_695x400_scrot](https://cloud.githubusercontent.com/assets/1371197/20228491/6dbc6052-a81f-11e6-8230-bbfe8a7c168f.png). At first I thought it was a font issue or something, but the options are literally blank
![2016-11-11-145933_393x166_scrot](https://cloud.githubusercontent.com/assets/1371197/20228506/84464cf2-a81f-11e6-8e12-74f10674bb9a.png)

As far as I can tell selecting a blank option doesn't do anything, so it's just an aesthetic thing.

**Comment by Ben3eeE** [comment] 2016-11-11 20:08
This is a duplicate of https://github.com/atom/tabs/issues/284. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-11-11 20:08 UTC
