### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Documents/Mayo2017/fondo/fondoPADCpos.txt' that ha...

### ISSUE THREAD

**Issue by psantarita** [atom/tabs#443] opened 2017-05-23 19:54 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.0

### Stack Trace

Uncaught Error: Adding a pane item with URI '/home/pedrosantarita/Documents/Mayo2017/fondo/fondoPADCpos.txt' that has already been destroyed

```
At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:25917

Error: Adding a pane item with URI '/home/pedrosantarita/Documents/Mayo2017/fondo/fondoPADCpos.txt' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/opt/atom/resources/app/src/pane.js:493:1)
    at Pane.module.exports.Pane.activateItem (/opt/atom/resources/app/src/pane.js:468:1)
    at Immediate.<anonymous> (/opt/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:701:1)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -0:06.8.0 tabs:close-all-tabs (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```

```

**Comment by psantarita** [comment] 2017-05-24 04:48
Hi!

I think I know what the problem was, the file I was trying to read was a 12
million line text file so it was kinda my fault.

regards

**Comment by Ben3eeE** [comment] 2017-08-12 18:34
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-12 18:34 UTC
Labels: more-information-needed, uncaught-exception
