### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/work/phalcon-topiframe.loc/app/server-bundle/serve...

### ISSUE THREAD

**Issue by jt3k** [atom/tabs#427] opened 2017-03-30 09:01 UTC
[Enter steps to reproduce:]

1. open and abort open large file
2. cannot close the tab.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.104.1

### Stack Trace

Uncaught Error: Adding a pane item with URI '/Users/a.gurtovoy/work/phalcon-topiframe.loc/app/server-bundle/server-bundle.js' that has already been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:474

Error: Adding a pane item with URI '/Users/a.gurtovoy/work/phalcon-topiframe.loc/app/server-bundle/server-bundle.js' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/app.asar/src/pane.js:474:15)
    at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:449:14)
    at TabBarView.module.exports.TabBarView.onMouseDown (/app.asar/node_modules/tabs/lib/tab-bar-view.js:678:19)
```

### Commands

```
  5x -3:03.4.0 core:move-down (input.hidden-input)
     -1:24.9.0 core:select-all (input.hidden-input)
     -1:24.5.0 core:paste (input.hidden-input)
     -1:23.2.0 core:undo (input.hidden-input)
     -1:22.2.0 core:paste (input.hidden-input)
     -1:20.4.0 core:undo (input.hidden-input)
     -1:18.6.0 core:paste (input.hidden-input)
     -1:14.9.0 core:undo (input.hidden-input)
     -1:14.3.0 core:paste (input.hidden-input)
     -1:11.7.0 command-palette:toggle (input.hidden-input)
     -1:10.1.0 core:confirm (input.hidden-input)
     -1:10.1.0 XO:Fix (input.hidden-input)
     -1:07.7.0 core:select-all (input.hidden-input)
     -1:06.9.0 core:copy (input.hidden-input)
     -0:42.4.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.file-colors.seti-icons.seti-roboto.seti-animate.theme-one-dark-syntax.theme-one-dark-ui)
     -0:29 core:copy (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
aesthetic-ui 2.0.0 
atom-beautify 0.29.17 
atom-like-brackets-editor 1.1.4 
atom-material-ui 1.3.9 
atom-monokai 0.10.9 
atom-ternjs 0.18.2 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-modules 1.6.8 
autocomplete-paths 1.0.5 
blame 0.10.2 
busy-signal 1.3.0 
color-tabs 0.1.8 
colorful-json 1.1.0 
comment 0.6.1 
duplicate-line-or-selection 0.9.0 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.1 
filecolor 0.4.0 
fold-functions 0.5.0 
fold-lines 0.2.2 
git-blame 0.4.12 
git-control 0.8.2 
git-plus 7.3.3 
git-status 0.3.4 
git-time-machine 1.5.9 
guess-indent 0.1.0 
highlight-bad-chars 1.0.5 
highlight-selected 0.13.1 
hyperclick 0.0.40 
indent-detective 0.1.0 
indent-guide-improved 1.4.12 
indent-toggle-on-paste 0.1.3 
indent-tooltip 0.2.1 
intentions 1.1.2 
js-hyperclick 1.10.1 
language-dot-template 0.2.0 
language-javascript-jsx 0.3.7 
language-mjml 1.9.0 
language-plantuml 0.2.0 
language-postcss 1.3.1 
language-pug 0.0.21 
language-volt 0.2.2 
lines 0.13.1 
linter 2.1.2 
linter-eslint 8.1.4 
linter-ui-default 1.2.2 
linter-xo 0.22.0 
markdown-folder 0.5.0 
markdown-scroll-sync 2.1.2 
monokai 0.22.0 
monokai-seti 0.7.0 
motepair 0.23.0 
npm-install 4.0.3 
npm-plus 0.4.0 
pigments 0.39.1 
plantuml-viewer 0.7.1 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
prompt-big-file 0.3.0 
react 0.16.2 
react-snippets 0.7.2 
remember-folds 0.3.0 
semanticolor 3.4.10 
set-syntax 0.3.2 
seti-ui 1.7.0 
simple-drag-drop-text 0.3.4 
styles-highlighter 2.3.0 
Stylus 3.1.0 
stylus-autocompile 0.6.1 
sublime-block-comment 0.5.1 
svg-preview 0.11.0 
sync-settings 0.8.1 
tool-bar-markdown-writer 0.2.0 
trailing-spaces 0.4.0 
turbo-javascript 1.4.0 
umd-snippets 0.1.1 
```

**Comment by rsese** [comment] 2017-03-30 18:47
Looks like a duplicate of https://github.com/atom/tabs/issues/258 based on the stack trace?  If you can add your details and steps to reproduce in that issue, that would be great :v:

**Closed by rsese** 2017-03-30 18:47 UTC
