### ISSUE TITLE
I cannot disable setting Tab Scrolling

### ISSUE THREAD

**Issue by in-in** [atom/tabs#538] opened 2018-03-18 14:16 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I can not disable the "Tab Scrolling" setting. The "false" option does not save. After closing setting it turns to "platform".

### Steps to Reproduce

1. Open Settings -> Packages -> Tabs
2. Go to Tab Scrolling and choose false
3. Close this tab and open again (see gif below)

**Expected behavior:** Tab Scrolling stops working

**Actual behavior:** Nothing changes, and the option goes into the default state

**Reproduces how often:** everytime

### Versions

```bash
~|⇒ atom --version && apm --version
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.12
git 2.16.2

```
```bash
~|⇒ uname -pv
#32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64

```

### Additional Information

![tabs](https://user-images.githubusercontent.com/8797432/37566855-aa33352c-2acf-11e8-9d96-231b25156044.gif)

**Comment by Ben3eeE** [comment] 2018-03-18 16:55
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/311. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-03-18 16:55 UTC
Labels: duplicate
