### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Desktop/count_avg.do' that has already been destroyed

### ISSUE THREAD

**Issue by drayanaindra** [atom/tabs#445] opened 2017-05-29 07:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.0

### Stack Trace

Uncaught Error: Adding a pane item with URI '/Users/drayanaindra/Desktop/count_avg.do' that has already been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:493

Error: Adding a pane item with URI '/Users/drayanaindra/Desktop/count_avg.do' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:493:1)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:468:1)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:701:1)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -0:29.9.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-icons.seti-roboto.seti-animate.theme-one-dark-syntax.theme-seti-ui)
     -0:22.9.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.6.3 
atom-typescript 11.0.3 
autocomplete-python 1.8.63 
autoprefixer 3.7.0 
busy-signal 1.4.1 
color-picker 2.2.5 
django-templates 0.5.0 
emmet 2.4.3 
git-control 0.9.0 
intentions 1.1.2 
kite 0.25.0 
linter 2.1.4 
linter-pycodestyle 2.0.2 
linter-ui-default 1.6.0 
markdown-preview-plus 2.4.9 
python-autopep8 0.1.3 
python-indent 1.0.2 
seti-ui 1.8.0 
term 0.2.4 
```

**Comment by rsese** [comment] 2017-05-29 18:36
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates.  If you have any steps to reproduce and can reproduce in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), please let us know in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-29 18:36 UTC
