### ISSUE TITLE
Uncaught Error: Cannot find module 'dialog'Error: Cannot find module 'dialog'    at Function.Module._resolveFilename (module.js:344:15)    at Function.Module._load (module.js:286:25)    at Module.require (module.js:373:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)    at EventEmitter.emit (events.js:110:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)    at EventEmitter.emit (events.js:110:17)

### ISSUE THREAD

**Issue by oilee80** [atom/tabs#126] opened 2015-03-28 19:57 UTC
Tried to close a tab that I'd just created, dialog was probably to ask about saving the changes as I hadn't done that yet.

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.64.0

### Stack Trace

Uncaught Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:344:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:373:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:110:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:110:17)

```
At /Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77

Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:344:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:373:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:110:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:110:17)
  at metaToValue (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77:15)
  at Object.exports.require (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:157:34)
  at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom.js:682:23)
  at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:504:21)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:456:18)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -1:41.8 core:move-right (atom-text-editor.editor)
  4x -1:41.3 editor:move-to-beginning-of-word (atom-text-editor.editor)
     -1:39.4 editor:select-to-beginning-of-word (atom-text-editor.editor)
  5x -1:36.0 editor:move-to-end-of-word (atom-text-editor.editor)
  3x -1:35.2 editor:move-to-beginning-of-word (atom-text-editor.editor)
     -1:34.4 core:move-right (atom-text-editor.editor)
  2x -1:33.4 editor:select-to-end-of-word (atom-text-editor.editor)
     -1:31.9 core:select-right (atom-text-editor.editor)
     -1:29.4 core:save (atom-text-editor.editor)
     -1:28.1 pane:show-next-item (atom-text-editor.editor)
  9x -0:43.2 core:backspace (atom-text-editor.editor)
  5x -0:35.3 core:move-up (atom-text-editor.editor)
     -0:33.9 core:move-left (atom-text-editor.editor)
     -0:33.5 core:move-right (atom-text-editor.editor)
     -0:33.2 editor:select-to-beginning-of-word (atom-text-editor.editor)
     -0:06.6 core:close (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "~",
      "app/cache/",
      "silverstripe-cache"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v0.3.3
linter, v0.12.0
linter-eslint, v0.5.0
linter-php, v0.0.11
php-twig, v3.0.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-28 20:31
Duplicate of atom/tree-view#399, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-28 20:31 UTC
