### ISSUE TITLE
Extremely sluggish performance when dragging 'tabs' (splitting)

### ISSUE THREAD

**Issue by cosmix** [atom/tabs#404] opened 2016-12-21 20:25 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom freezes when 'dragging' tabs from one pane another (within the same window or across windows) or when attempting to create a pane through dragging.

### Steps to Reproduce

1. Launch Atom
2. Open two files.
3. Drag one of the tabs so that part of the existing editor viewport gets highlighted (split zone indicator).

**Expected behavior:** [What you expected to happen]

Fast performance while dragging

**Actual behavior:** [What actually happened]

Sluggish performance, very slow visual update of tab movement.

### Versions

This issue is probably a regression. It started recently and manifests itself in 1.12.7 on macOS 10.12.2.

**Comment by lee-dohm** [comment] 2016-12-24 19:32
I couldn't reproduce this using Atom v1.12.7 on Mac OS X 10.12.2. Do you have any more information you can share about when this happens? Large projects? Large files? Packages you have running?

**Comment by cosmix** [comment] 2016-12-24 19:35
I've got several packages, but I could repeatedly reproduce it in safe mode. Yes it did happen while I was working on a relatively large project with ~20-25 tabs open in two panes. Dragging a tab from one pane to the other took ages (no interactive visual 'feedback'), well after I lifted my finger off the mouse button. Then, several seconds later the tab was 'moved' to the destination/target pane. Let me know if you require any more information.

**Comment by Ben3eeE** [comment] 2016-12-24 21:03
Thanks for reaching out!

We have a PR open for improving the performance of the placeholder https://github.com/atom/tabs/pull/390

* Is this issue specific to the performance of the layout management when dragging tabs introduced in https://github.com/atom/tabs/pull/252? Or are you referring to the performance of placing the placeholder?
* Would you say that the performance drop you see is like https://github.com/atom/tabs/issues/226?
* If this is not the performance of the placeholder or a duplicate of https://github.com/atom/tabs/issues/226 could you provide a gif of the issue you are facing so we can see exactly what you are doing when you experience this issue?

**Comment by Ben3eeE** [comment] 2017-09-23 18:26
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tabs/issues/404#issuecomment-269100344. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by Ben3eeE** 2017-09-23 18:26 UTC
Labels: more-information-needed, needs-reproduction

**Comment by ha404** [comment] 2017-10-12 19:16
I experience this, but not in safe mode. I have about 20 packages. I tried disabling each package one by one but couldn't single out which one causes this. It feels as if the more I disabled, the less severe the problem. With everything enabled, the lag is really noticeable. Is there a problem with loading many packages?

**Comment by Ben3eeE** [comment] 2017-10-12 19:18
@ha404 Is the performance drop you notice the performance of placing the placeholder? We have a PR open to address this https://github.com/atom/tabs/pull/390

**Comment by ha404** [comment] 2017-10-12 19:22
@Ben3eeE omg that's it!

**Comment by bblack** [comment] 2020-08-25 18:33
I'm experiencing this slowness on
atom 1.50.0
electron 5.0.13
chrome 73.0.3683.121
node v12.0.0

Quitting then opening in safe mode, the slowness goes away.

Quitting from safe mode, then opening normally, the slowness is still gone. So maybe the problem worsens the longer Atom is open?
