### ISSUE TITLE
Preview tabs setting and files opened from the context menu or dragged inside the editor.

### ISSUE THREAD

**Issue by YAmikep** [atom/tabs#193] opened 2015-07-04 20:52 UTC
When the "Use Preview Tabs" setting is enabled, all the files I open from the context menu on Windows (Right click -> Open with Atom) or the files I drag and drop inside Atom stay in preview mode.
This brings another issue: if you select several files and drag them into Atom to look at them, only one preview tab is created so you cannot see all the files.
I would expect the files to be open and not in preview mode in those cases.

**Comment by einarmagnus** [comment] 2015-07-13 11:02
Same goes for files opened from the command line. If I run `atom somefile.md` I expect it to stay open as if I double-clicked it in the project drawer, right now it doesn't.

**Comment by einarmagnus** [comment] 2015-07-13 11:09
I see now that this is a duplicate of #170 and that someone is working on it! Great!

**Comment by lee-dohm** [comment] 2015-07-13 15:27
Thanks @einarmagnus. You're correct, this is a duplicate of #170. Closing this as duplicate.

**Closed by lee-dohm** 2015-07-13 15:27 UTC
Labels: bug
