### ISSUE TITLE
Uncaught Error: Cannot find module 'dialog'Error: Cannot find module 'dialog'    at Function.Module._resolveFilename (module.js:351:15)    at Function.Module._load (module.js:293:25)    at Module.require (module.js:380:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)    at EventEmitter.emit (events.js:119:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)    at EventEmitter.emit (events.js:119:17)

### ISSUE THREAD

**Issue by jarrar** [atom/tabs#125] opened 2015-03-21 00:41 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.9.5
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.67.0

### Stack Trace

Uncaught Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)

```
At /Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77

Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)
    at metaToValue (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77:15)
    at Object.exports.require (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:157:34)
    at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom.js:705:23)
    at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:507:21)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:456:18)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:179:22)
    at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
    at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)
```

### Commands

```
     -0:22.6 core:paste (atom-text-editor.editor)
  2x -0:20.1 core:move-up (atom-text-editor.editor)
     -0:18.4 core:move-left (atom-text-editor.editor)
     -0:17.5 core:backspace (atom-text-editor.editor)
     -0:16.7 core:move-down (atom-text-editor.editor)
     -0:16.1 core:move-left (atom-text-editor.editor)
     -0:15.7 core:backspace (atom-text-editor.editor)
  2x -0:14.5 core:move-up (atom-text-editor.editor)
     -0:11.7 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.5.18

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-21 01:53
Duplicate of atom/tree-view#399, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-21 01:53 UTC
