### ISSUE TITLE
Uncaught Error: Adding a pane item with URI that has already been destroyed

### ISSUE THREAD

**Issue by asbjornu** [atom/tabs#487] opened 2017-07-14 14:33 UTC
I was just closing a few tabs while this happened. No idea whether it's reproducible.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI '~/Dev/tmp/Redacted.yml' that has already been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:493

Error: Adding a pane item with URI '~/Dev/tmp/Redacted.yml' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:493:21)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:468:20)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
  4x -0:16 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
file-icons 2.1.8 
file-types 0.5.5 
hard-wrap 1.1.0 
language-batch 0.4.0 
language-markdown 0.23.0 
language-plantuml 0.2.0 
language-powershell 4.0.0 
markdown-preview-plus 2.4.9 
plantuml-viewer 0.7.1 
sorter 1.1.0 
split-diff 1.4.3 
wakatime 7.0.3 
xml-decoder 1.1.0 
```

**Comment by rsese** [comment] 2017-07-17 21:26
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/tabs/issues/444 so you may want to subscribe there for updates.  It sounds like you ran into this one time but if it ends up being reproducible for you, please let us know in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-17 21:26 UTC
