### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/alooma/integrations/venv/lib/python2.7/site-packag...

### ISSUE THREAD

**Issue by israelha** [atom/tabs#505] opened 2017-08-06 10:47 UTC
just reopened Atom : X
**Atom**: 1.19.0-beta5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.10.5
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI '/Users/israelhamou/alooma/integrations/venv/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py' that has already been destroyed

```
At /Users/israelhamou/Downloads/Atom Beta.app/Contents/Resources/app/src/pane.js:514

Error: Adding a pane item with URI '/Users/israelhamou/alooma/integrations/venv/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Users/israelhamou/Downloads/Atom Beta.app/Contents/Resources/app/src/pane.js:514:21)
    at Pane.module.exports.Pane.activateItem (/Users/israelhamou/Downloads/Atom Beta.app/Contents/Resources/app/src/pane.js:489:20)
    at Immediate.<anonymous> (/Users/israelhamou/Downloads/Atom Beta.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
  3x -0:18.6.0 core:close (atom-pane.pane.active)
```

### Non-Core Packages

```
autocomplete-java 1.2.7 
autocomplete-python 1.9.1 
busy-signal 1.4.3 
Chromodynamics 0.0.11 
hyperclick 0.1.3 
intentions 1.1.5 
kite 0.32.1 
linter 2.2.0 
linter-javac 1.9.4 
linter-pylama 0.9.3 
linter-pylint 2.1.0 
linter-ui-default 1.6.3 
MagicPython 1.0.11 
python-indent 1.1.0 
python-yapf 0.14.0 
vim-mode-plus 0.96.2 
vim-mode-plus-ex-mode 0.9.1 
```

**Comment by rsese** [comment] 2017-08-07 20:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates - if you have consistent steps to reproduce in safe mode, please let us know in the issue!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-07 20:28 UTC
