### ISSUE TITLE
Click on tab steals focus from editor

### ISSUE THREAD

**Issue by xeron** [atom/tabs#140] opened 2015-05-14 04:22 UTC
Atom: 0.198.0
OSX: 10.10.3

Editor looses focus after clicking on tab so I'm not able to type anymore and required to press Tab key or to click inside editor area.

**Comment by mnquintana** [comment] 2015-05-14 10:20
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/6662 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-14 10:20 UTC
Labels: duplicate
