### ISSUE TITLE
Uncaught Error: Adding a pane item with URI 'C:/xampp\htdocs\hp_projects\egAdmin\application\cont...

### ISSUE THREAD

**Issue by pergsify** [atom/tabs#451] opened 2017-06-06 10:57 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.0

### Stack Trace

Uncaught Error: Adding a pane item with URI 'C:\xampp\htdocs\hp_projects\egAdmin\application\controllers\Campaigns_flexible_setup.php' that has already been destroyed

```
At C:\Users\elman-file\AppData\Local\atom\app-1.17.2\resources\app\src\pane.js:493

Error: Adding a pane item with URI 'C:\xampp\htdocs\hp_projects\egAdmin\application\controllers\Campaigns_flexible_setup.php' that has already been destroyed
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:493:1)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:468:1)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/tabs/lib/tab-bar-view.js:701:1)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
  2x -8:06.3.0 editor:move-to-first-character-of-line (input.hidden-input)
     -8:05.8.0 core:select-down (input.hidden-input)
     -8:05.4.0 core:delete (input.hidden-input)
  2x -2:24.6.0 core:move-down (div.tool-panel.tree-view)
  2x -2:23.9.0 tree-view:collapse-directory (div.tool-panel.tree-view)
     -2:22.9.0 tree-view:expand-item (div.tool-panel.tree-view)
  3x -2:22.4.0 core:move-down (div.tool-panel.tree-view)
     -2:14.9.0 find-and-replace:show (input.hidden-input)
  2x -2:12.5.0 core:confirm (input.hidden-input)
     -2:06.1.0 editor:consolidate-selections (input.hidden-input)
     -2:06.1.0 core:ca

**Comment by rsese** [comment] 2017-06-06 18:29
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-06 18:29 UTC
