### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by whzhyh** [atom/tabs#96] opened 2014-12-11 09:22 UTC
Uncaught TypeError: Cannot read property 'destroy' of undefined

**Atom Version**: 0.156.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.57.0
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:227

TypeError: Cannot read property 'destroy' of undefined
  at TabBarView.module.exports.TabBarView.removeTabForItem (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:227:28)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:125:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:384:20)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:443:16)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:422:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:604:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:643:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:284:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by avdg** [comment] 2017-01-25 22:19
Got bugs like this when tabs are closing (especially when doing `close all`).

**Comment by avdg** [comment] 2017-01-25 22:21
Stack trace:

```
TypeError: Cannot read property 'destroy' of undefined
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.destroyMarker (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:189:34)
    at C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:366:37
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.destroyMarker (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:365:34)
    at Marker.module.exports.Marker.destroy (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\text-buffer\lib\marker.js:269:18)
    at DisplayMarker.module.exports.DisplayMarker.destroy (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\text-buffer\lib\display-marker.js:27:25)
    at C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:50:23
    at Set.forEach (native)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.clear (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:49:40)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.destroy (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:37:12)
    at displayMarkerLayersById.forEach (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\text-buffer\lib\display-layer.js:115:59)
    at Map.forEach (native)
    at DisplayLayer.destroy (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\text-buffer\lib\display-layer.js:115:34)
    at TextEditor.module.exports.TextEditor.destroyed (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\src\text-editor.js:540:25)
    at TextEditor.module.exports.Model.destroy (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\src\model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\src\pane.js:660:18)
    at TabBarView.module.exports.TabBarView.closeTab (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:333:26)
    at TabBarView.module.exports.TabBarView.closeAllTabs (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:464:27)
    at Object.TabBarView.addElementCommands.tabs:close-all-tabs (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:111:26)
    at HTMLUListElement.commandsWithPropagationStopped.(anonymous function) (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:77:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\src\atom-environment.js:1164:28)
    at EventEmitter.outerCallback (C:\Users\Anthony\AppData\Local\atom\app-1.14.0-beta2\resources\app.asar\src\application-delegate.js:333:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by mokutsu** [comment] 2017-02-23 14:50
Hi, I'm getting the same issue as @avdg, `Uncaught TypeError: Cannot read property 'destroy' of undefined`, it looks like a slightly difference stack trace?

```
TypeError: Cannot read property 'destroy' of undefined
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.destroyMarker (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:189:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:366:37
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.destroyMarker (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:365:34)
    at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:269:18)
    at DisplayMarker.module.exports.DisplayMarker.destroy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:27:25)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:50:23
    at Set.forEach (native)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.clear (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:49:40)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.destroy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:37:12)
    at displayMarkerLayersById.forEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:115:59)
    at Map.forEach (native)
    at DisplayLayer.destroy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:115:34)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:540:25)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:660:18)
    at TabBarView.module.exports.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

**Comment by avdg** [comment] 2017-02-23 18:24
@mokutsu is it reproducible in any way? Did you close a tab?

**Comment by jefe-spain** [comment] 2017-03-03 11:04
@avdg @mokutsu  , Did you fix the problem?, I've got the same problem when I split the tabs and I try to close them or scroll.

**Comment by avdg** [comment] 2017-03-03 19:11
I'm not maintaining this code

**Closed as completed** 2018-12-12 22:26 UTC
Labels: uncaught-exception
