### ISSUE TITLE
Can only re-open one file at a time with 'preview tabs' enabled

### ISSUE THREAD

**Issue by zyklus** [atom/tabs#209] opened 2015-09-09 09:30 UTC
If I try to re-open (un-close) multiple files via `cmd+shift+t`, and `preview tabs` is enabled, it re-opens one as a preview tab and just cycles between the last two closed files.

**Comment by 50Wliu** [comment] 2015-09-09 14:57
Duplicate of #163, please subscribe there for updates.

**Closed by 50Wliu** 2015-09-09 14:57 UTC
