### ISSUE TITLE
Uncaught TypeError: this.iconName.split is not a function

### ISSUE THREAD

**Issue by ramz225** [atom/tabs#341] opened 2016-06-06 22:30 UTC
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:325
Hide Stack Trace
TypeError: this.iconName.split is not a function
    at tabs-tab.module.exports.TabView.updateIcon (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:325:63)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:123:24
    at HTMLEditor.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/node_modules/emissary/lib/emitter.js:118:15)
    at HTMLEditor.module.exports.HTMLEditor.updateIcon (/Users/Tayler_Ramsay/.atom/packages/browser-plus/lib/browser-plus-model.coffee:69:8)
    at webview.<anonymous> (/Users/Tayler_Ramsay/.atom/packages/browser-plus/lib/browser-plus-view.coffee:233:16)
    at WebViewImpl.dispatchEvent (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:188:29)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/guest-view-internal.js:56:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/guest-view-internal.js:67:28)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)

**Comment by 50Wliu** [comment] 2016-06-07 03:17
This is a duplicate of skandasoft/browser-plus#75 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-07 03:17 UTC
