### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Documents\Clicker\public\geographyprojectfiles\mar...

### ISSUE THREAD

**Issue by MinecraftBoxGuy** [atom/tabs#475] opened 2017-07-03 16:44 UTC
[Enter steps to reproduce:]

1. Open large file and other tabs
2. Spam close other tabs (Only happened on one occasion but this is what I did)

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI 'C:\Users\Richard\Documents\Clicker\public\geographyprojectfiles\markdown\exports.md' that has already been destroyed

```
At C:\Users\Richard\AppData\Local\atom\app-1.18.0\resources\app\src\pane.js:493

Error: Adding a pane item with URI 'C:\Users\Richard\Documents\Clicker\public\geographyprojectfiles\markdown\exports.md' that has already been destroyed
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:493:21)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:468:20)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
 11x -9:56.5.0 core:backspace (input.hidden-input)
     -9:17.6.0 intentions:highlight (input.hidden-input)
     -9:17.6.0 core:save (input.hidden-input)
     -1:18.6.0 tree-view:add-file (div.header.list-item)
     -1:16.6.0 core:backspace (input.hidden-input)
     -1:15.1.0 core:confirm (input.hidden-input)
     -0:58.7.0 intentions:highlight (input.hidden-input)
     -0:58.4.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-clock 0.1.11 
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
busy-signal 1.4.3 
close-on-left 0.8.0 
color-picker 2.2.5 
dark-side-of-the-moon-syntax 0.6.26 
emmet 2.4.3 
file-icons 2.1.8 
git-plus 7.9.3 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
javascript-snippets 1.2.1 
jsformat 0.9.3 
language-pug 0.0.21 
linter 2.2.0 
linter-eslint 8.2.1 
linter-jshint 3.1.2 
linter-sass-lint 1.7.4 
linter-tidy 2.3.1 
linter-ui-default 1.6.2 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
spell-check-project 0.7.0 
todo-show 1.11.0 
webbox-color 0.5.9 
```

I closed all other tabs with a big file open

**Comment by rsese** [comment] 2017-07-03 21:57
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates - it sounds like you can't reproduce now but if you end up with consistent steps to reproduce, please let us know in the issue!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-03 21:57 UTC
