### ISSUE TITLE
File selection closes a tab

### ISSUE THREAD

**Issue by Xalbi** [atom/tabs#297] opened 2016-04-05 15:08 UTC
Hello,

When i select a file that have a same name as one of "currently open file tabs" but with different extension.. the currently open file is replaced with the new one.
PS: i did not have this problem before the 1.6.2 version.. 
Example : toto.js replaces toto.xml  

Thnx

**Comment by robblue2x** [comment] 2016-04-11 09:22
I noticed the same problem after upgrading to 1.6.2 today

**Comment by robblue2x** [comment] 2016-04-12 11:40
Works in atom v1.5.4, tabs v0.88.0

**Comment by robblue2x** [comment] 2016-04-12 12:24
I tested tabs v0.92.1 in atom v1.5.4 and it works fine, suggesting the problem is not in this module

**Comment by Xalbi** [comment] 2016-04-12 13:44
Actually, i noticed something new, and am starting to think that, maybe this is not a real issue...
in fact, the replacement thing happens when the first file is selected/opened by one click ( the tab name has an italic font style).
But when the selection (of the first file) is made by double click, the new file is opened in new tab as usual (the tab name has a normal font style).

**Comment by robblue2x** [comment] 2016-04-12 13:54
I did read something in the commits about a 'preview tab' maybe single click is for preview and double click opens the file

**Comment by robblue2x** [comment] 2016-04-12 14:07
This is a feature.
Single click previews the file, double click opens it. Double clicking on a preview tab will open it.
Can you close this issue?

**Closed** 2016-04-12 14:37 UTC
