### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by rtuider** [atom/tabs#115] opened 2015-02-03 11:58 UTC
1. Switch tab from "setting" to a "js"-tab

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.64.0

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of undefined

```
At c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\space-pen\lib\space-pen.js:516

TypeError: Cannot read property 'style' of undefined
  at [object Object].$.fn.isHidden (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\space-pen\lib\space-pen.js:516:20)
  at [object Object].$.fn.isVisible (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\space-pen\lib\space-pen.js:511:18)
  at ESLintGutterView.module.exports.ESLintGutterView.renderErrors (c:\Users\d050479\.atom\packages\eslint\lib\eslint-gutter-view.coffee:52:27)
  at atom-text-editor.<anonymous> (c:\Users\d050479\.atom\packages\eslint\lib\eslint-gutter-view.coffee:1:1)
  at atom-text-editor.handler (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\src\space-pen-extensions.js:112:34)
  at atom-text-editor.jQuery.event.dispatch (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at atom-text-editor.elemData.handle (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\src\command-registry.js:156:19)
  at TextEditorView.jQuery.fn.trigger (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\src\space-pen-extensions.js:64:23)
  at [object Object].module.exports.React.createClass.componentDidUpdate (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor-component.js:273:54)
  at CallbackQueue.mixInto.notifyAll (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.replaceState (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\ReactCompositeComponent.js:878:20)
  at [object Object].ReactCompositeComponentMixin.setState (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\ReactCompositeComponent.js:850:10)
  at [object Object].module.exports.React.createClass.focused (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor-component.js:619:14)
  at [object Object].boundMethod [as focused] (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\react-atom-fork\lib\ReactCompositeComponent.js:1295:21)
  at atom-text-editor.TextEditorElement.focused (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor-element.js:199:55)
  at atom-pane.PaneElement.activeItemChanged (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\src\pane-element.js:125:25)
  at Emitter.module.exports.Emitter.emit (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\src\pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\src\pane.js:328:21)
  at tabs-tab.<anonymous> (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\tabs\lib\tab-bar-view.js:184:24)
  at space-pen-ul.jQuery.event.dispatch (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-ul.elemData.handle (c:\Users\d050479\AppData\Local\atom\app-0.176.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -5:27.4 tree-view:expand-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:55.6 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "eslint"
    ],
    "projectHome": "c:\\Users\\d050479\\git"
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v0.3.0
file-icons, v1.4.8
grunt-runner, v0.6.0
incremental-search, v4.2.0
minimap, v3.5.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment] 2015-02-03 12:57
Could you please try to reproduce this in safe mode (`atom --safe`)?

**Comment by rtuider** [comment] 2015-02-04 10:40
@kevinsawicki because this was a generated exception and I simply clicked on "create issue" - like this functionality :)

**Comment by rtuider** [comment] 2015-02-04 10:48
@50Wliu error doesn't occur. I also deactivated the eslint plugin again

**Comment by benogle** [comment] 2015-02-04 17:09
The `eslint` package is disabled. Maybe it isnt cleaning up after itself on deactivate?

@rtuider, did you disable the `eslint` package and keep working in the editor when you saw this?

**Comment by rtuider** [comment] 2015-02-05 13:32
@benogle no I disabled it after getting this errors

**Comment by benogle** [comment] 2015-02-05 19:10
Did you get the error multiple times? Looks like eslint was disabled at the time of this error, and that's why it pointed at the tabs package rather than the eslint package.

**Comment by izuzak** [comment] 2015-06-10 12:37
Going to close this out since it should have been reported on eslint.

**Closed by izuzak** 2015-06-10 12:37 UTC
Labels: more-information-needed
