### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Desktop/search_test/search-results.php' that has a...

### ISSUE THREAD

**Issue by andydevlinsmith** [atom/tabs#492] opened 2017-07-20 16:17 UTC
I noticed this error since upgrading some Atom packages and installing phpcs. I see slow loading of pages and occasional crashes when using with PHPunit. Sorry if this isn't more specific.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.10.5
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI '/Users/andy.smith/Desktop/search_test/search-results.php' that has already been destroyed

```
At /Users/andy.smith/Downloads/Atom 2.app/Contents/Resources/app/src/pane.js:493

Error: Adding a pane item with URI '/Users/andy.smith/Desktop/search_test/search-results.php' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Users/andy.smith/Downloads/Atom 2.app/Contents/Resources/app/src/pane.js:493:21)
    at Pane.module.exports.Pane.activateItem (/Users/andy.smith/Downloads/Atom 2.app/Contents/Resources/app/src/pane.js:468:20)
    at Immediate.<anonymous> (/Users/andy.smith/Downloads/Atom 2.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
  3x -8:02.7.0 core:copy (span.syntax--entity.syntax--name.syntax--function.syntax--php)
     -2:53.4.0 core:paste (input.hidden-input)
     -2:48.7.0 find-and-replace:show (input.hidden-input)
 14x -0:55.4.0 core:move-down (input.hidden-input)
     -0:50.8.0 editor:consolidate-selections (input.hidden-input)
     -0:50.8.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-preview 2.10.2 
busy-signal 1.4.3 
intentions 1.1.2 
linter 2.2.0 
linter-flake8 2.2.1 
linter-js-yaml 1.2.7 
linter-jshint 3.1.5 
linter-php 1.3.2 
linter-phpcs 1.6.7 
linter-ui-default 1.6.2 
script 3.15.0 
```

**Comment by rsese** [comment] 2017-07-20 20:50
Thanks for the report!

> I noticed this error since upgrading some Atom packages and installing phpcs. I see slow loading of pages and occasional crashes when using with PHPunit. Sorry if this isn't more specific.

No problem at all - the duplicate issue is noted below so f you have consistent steps to reproduce the Atom specific error in safe mode (`atom --safe`) feel free to let us know in the issue.

---

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444 so you may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-20 20:50 UTC
