### ISSUE TITLE
Uncaught Error: Adding a pane item with URI 'Z:/CS162\assignment4\tile.h' that has already been d...

### ISSUE THREAD

**Issue by thegrims** [atom/tabs#442] opened 2017-05-21 10:12 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.0

### Stack Trace

Uncaught Error: Adding a pane item with URI 'Z:\CS162\assignment4\tile.h' that has already been destroyed

```
At C:\Users\grims_000\AppData\Local\atom\app-1.17.0\resources\app\src\pane.js:493

Error: Adding a pane item with URI 'Z:\CS162\assignment4\tile.h' that has already been destroyed
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.17.0/resources/app/src/pane.js:493:1)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.17.0/resources/app/src/pane.js:468:1)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:701:1)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-05-31 23:07
Thanks for taking the time to contribute!

Going to go ahead and close as a duplicate of https://github.com/atom/tabs/issues/258 but if you can reproduce, it would be great if you can share steps to repro in the issue :v:

---

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/258. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-31 23:07 UTC
