### ISSUE TITLE
Suggestion: Opening file from fuzzy finder should not open as Preview tab

### ISSUE THREAD

**Issue by afinne** [atom/tabs#178] opened 2015-06-12 11:54 UTC
When using Cmd-P or Cmd-T to activate the fuzzy finder, and choose a file from there, at least I would like it to open as a "normal" tab and not in "preview mode". 

It feels like preview tabs is great when clicking through the tree view, but when you type the name of a file and select it, you most likely want it to be "normal".

Is this something that could be added?

**Comment by mnquintana** [comment] 2015-06-12 11:56
This is a duplicate of https://github.com/atom/tabs/issues/164 - please subscribe there for updates.

**Closed by mnquintana** 2015-06-12 11:56 UTC
