### ISSUE TITLE
bad css for .tab-bar:after

### ISSUE THREAD

**Issue by mark-hahn** [atom/tabs#105] opened 2015-01-10 00:58 UTC
I can't find it in the source code, but there is a style in `.tab-bar:after` that is drawing a wide bar using `position:fixed`.  This causes the bar to appear over other things when the tab-bar is in a different position on the screen.  I tested this with `atom --safe` and the `.tab-bar:after` is still there.

![sgsdv](https://cloud.githubusercontent.com/assets/811455/5689736/5289dc3a-9820-11e4-8102-f8ceac46bd77.gif)

See https://github.com/mark-hahn/command-toolbar/issues/2

**Comment by simurai** [comment] 2015-01-10 12:50
It looks like this comes from the Atome Dark UI theme and is a dupe of https://github.com/atom/atom-dark-ui/pull/37.

**Closed by simurai** 2015-01-10 12:50 UTC
