### ISSUE TITLE
Uncaught TypeError: this.iconName.split is not a function

### ISSUE THREAD

**Issue by oTsogbadrakhChinzorig** [atom/tabs#346] opened 2016-06-15 03:28 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.96.0

### Stack Trace

Uncaught TypeError: this.iconName.split is not a function

```
At C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tabs\lib\tab-view.js:325

TypeError: this.iconName.split is not a function
    at tabs-tab.module.exports.TabView.updateIcon (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tabs\lib\tab-view.js:325:63)
    at C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tabs\lib\tab-view.js:123:24
    at HTMLEditor.module.exports.Emitter.emit (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\node_modules\emissary\lib\emitter.js:118:15)
    at HTMLEditor.module.exports.HTMLEditor.updateIcon (file:///C:/Users/user/.atom/packages/browser-plus/lib/browser-plus-model.coffee:69:8)
    at webview.<anonymous> (file:///C:/Users/user/.atom/packages/browser-plus/lib/browser-plus-view.coffee:233:16)
    at WebViewImpl.dispatchEvent (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\atom.asar\renderer\lib\web-view\web-view.js:188:29)
    at dispatchEvent (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\atom.asar\renderer\lib\web-view\guest-view-internal.js:56:11)
    at EventEmitter.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.8.0\resources\atom.asar\renderer\lib\web-view\guest-view-internal.js:67:28)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -8:03.4.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -7:49.8.0 application:open-file (atom-text-editor.editor.is-focused)
     -7:44.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  8x -7:38.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:33.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:33.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:32.4.0 application:open-folder (atom-text-editor.editor.is-focused)
     -5:51.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -5:51.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -5:49.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:15.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:59.5.0 symbol-gen:generate (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:24.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:18.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 45x -0:22.3.0 navigate:forward (atom-text-editor.editor.is-focused)
     -0:08.5.0 navigate:browser (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.8
auto-detect-indentation, v1.1.0
autoclose-html, v0.23.0
autocomplete-paths, v1.0.2
browser-plus, v0.0.60
emmet, v2.4.3
file-icons, v1.7.14
file-types, v0.5.1
git-control, v0.7.1
git-log, v0.4.1
git-plus, v5.15.0
highlight-column, v0.5.1
japanese-wrap, v0.2.7
linter, v1.11.10
linter-coffeelint, v1.1.2
linter-erb, v1.0.2
linter-htmlhint, v1.2.0
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-scss-lint, v3.0.4
minimap, v4.24.6
navigate, v0.1.15
pigments, v0.29.2
pretty-json, v1.4.1
project-manager, v2.9.7
rails-i18n-autocomplete, v0.3.0
remote-sync, v4.1.2
rest-client, v1.1.1
ruby-define-method, v0.2.2
symbol-gen, v1.3.1
tabs-to-spaces, v1.0.2
tree-view-git-status, v1.0.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-06-15 12:32
This is a duplicate of skandasoft/browser-plus#75 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-15 12:32 UTC

**Comment by hellodabin** [comment] 2016-06-30 08:37
this is a error！
