### ISSUE TITLE
Uncaught Error: Adding a pane item with URI 'D:/Private\01_PersonalGithub\업무\한글_위키_QA_쿼리패턴_v0.1.m...

### ISSUE THREAD

**Issue by gilje** [atom/tabs#447] opened 2017-06-01 04:15 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-beta2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.0

### Stack Trace

Uncaught Error: Adding a pane item with URI 'D:\Private\01_PersonalGithub\업무\한글_위키_QA_쿼리패턴_v0.1.md' that has already been destroyed

```
At C:\Users\gilje\AppData\Local\atom\app-1.18.0-beta2\resources\app\src\pane.js:493

Error: Adding a pane item with URI 'D:\Private\01_PersonalGithub\업무\한글_위키_QA_쿼리패턴_v0.1.md' that has already been destroyed
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/src/pane.js:493:21)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/src/pane.js:468:20)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.18.0-beta2/resources/app/node_modules/tabs/lib/tab-bar-view.js:701:30)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-clock 0.1.8 
atom-mdtoc 0.8.3 
chester-atom-syntax 0.1.1 
code-peek 1.4.20 
color-picker 2.2.5 
highlight-selected 0.13.1 
language-markdown 0.22.0 
markdown-preview-enhanced 0.12.5 
package-sync 1.1.0 
pigments 0.39.1 
pretty-json 1.6.3 
pubster-syntax 3.0.1 
seti-syntax 1.1.3 
seti-ui 1.8.0 
tool-bar-markdown-writer 0.2.0 
```

**Comment by rsese** [comment] 2017-06-01 22:20
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-01 22:20 UTC
