### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received ~

### ISSUE THREAD

**Issue by meafmira** [atom/tabs#436] opened 2017-04-16 16:48 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.104.2

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
  at assertPath (path.js:7:11)
  at Object.join (path.js:1213:7)
  at Object.tildify (/app.asar/node_modules/fs-plus/lib/fs-plus.js:64:39)
  at Workspace.updateWindowTitle (/app.asar/src/workspace.js:259:24)
  at observeActivePaneItem.item (/app.asar/src/workspace.js:184:12)
  at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at /app.asar/src/pane-container.js:348:27
  at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
  at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:452:21)
  at TabBarView.module.exports.TabBarView.onMouseDown (/app.asar/node_modules/tabs/lib/tab-bar-view.js:678:19)

```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.22 
atom-wallaby 1.0.16 
busy-signal 1.3.0 
dash 1.7.1 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.57.3 
language-graphql 0.8.0 
language-haskell 1.12.1 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.8.0 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.1.4 
linter-coffeelint 1.2.1 
linter-eslint 8.1.6 
linter-ui-default 1.2.3 
MagicPython 1.0.9 
merge-conflicts 1.4.4 
mocha-test-runner 0.5.1 
nuclide 0.217.0 
nuclide-format-js 0.0.36 
nuclide-test-runner-mocha 0.1.1 
raml 0.2.0 
set-syntax 0.3.2 
sort-lines 0.14.0 
sync-settings 0.8.1 
terminal-plus 0.14.5 
tool-bar 1.1.0 
wakatime 6.0.13 
```

**Comment by rsese** [comment] 2017-04-17 07:31
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/435. You may want to subscribe there for updates - if you have different steps to reproduce, please mention it in that issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-04-17 07:31 UTC
