### ISSUE TITLE
Need setting to disable MRU tab behaviour

### ISSUE THREAD

**Issue by Alhadis** [atom/tabs#301] opened 2016-04-13 22:36 UTC
[v1.7.0](https://github.com/atom/atom/releases/tag/v1.7.0) introduced a new tab-switching behaviour where a pane's tabs are cycled through in the order they were most recently-used.

There doesn't appear to be a setting to turn this off, though (to revert to the previous behaviour of cycling through each pane's *physical* order).

Is there a way of fixing this?

**Comment by 50Wliu** [comment] 2016-04-13 22:38
This is a duplicate of atom/atom#11035 - please subscribe there for updates.

**Closed by 50Wliu** 2016-04-13 22:38 UTC

**Comment by Alhadis** [comment] 2016-04-13 22:39
Sorry. :( This package's name is slightly deceptive...
