### ISSUE TITLE
Uncaught Error: Replacing non-existent child

### ISSUE THREAD

**Issue by slawek50** [atom/tabs#396] opened 2016-11-08 11:16 UTC
Steps to reproduce :
1. Open atom
2. Open two tabs
3. Move one tab to split the view using mouse

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.2
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.101.0

### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /Users/distiller/atom/out/app/src/pane-container.coffee:173

Error: Replacing non-existent child
    at PaneContainer.module.exports.PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:173:15)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:904:21)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:884:19)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/layout.js:44:27)
    at Object.module.exports.end (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/layout.js:50:10)
    at tabs-tab.ondragend (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:54:23)
```

### Commands

```
     -2:40.7.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -2:40.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:26.8.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -1:25.8.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -1:25.4.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -1:25.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:24.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:24 core:move-right (atom-text-editor.editor.is-focused)
     -1:23.6.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -1:22.7.0 core:delete (atom-text-editor.editor.is-focused)
     -1:21.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:19.3.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:07.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "disabledPackages": [
      "linter-rubocop",
      "welcome"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_modules"
    ],
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0 (active)
duplicate-line-or-selection, v0.8.0 (active)
file-type-icons, v1.3.3 (active)
language-babel, v2.47.0 (active)
language-slim, v0.5.0 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-rubocop, v0.5.0 (inactive)
php-twig, v4.0.0 (active)
pretty-json, v1.6.1 (active)
project-manager, v3.3.3 (active)
tabs-to-spaces, v1.0.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-11-08 17:30
Hi @slawek50, what were you doing when this occurred?

**Comment by slawek50** [comment] 2016-11-09 14:31
I tried to split the view by moving a tab and using the mouse.

**Comment by slawek50** [comment] 2016-11-12 14:16
For information, this bug have disappeared only after removing the `~/.atom` folder.

**Comment by 50Wliu** [comment] 2016-11-12 18:46
Ok.  Then it sounds like one of your packages was causing this error.  As it's no longer reproducible I'm going to close this, but if it happens again please comment here.

**Closed by 50Wliu** 2016-11-12 18:46 UTC
Labels: needs-reproduction, uncaught-exception

**Comment by tremendus** [comment] 2017-06-21 17:42
This just happened to me. 
```
Uncaught Error: Replacing non-existent child
/Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:145
Hide Stack Trace
Error: Replacing non-existent child
    at PaneContainer.replaceChild (/Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:145:47)
    at Pane.module.exports.Pane.split (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:984:27)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:964:25)
    at Object.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/tabs/lib/layout.js:50:33)
    at Object.end (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/tabs/lib/layout.js:56:16)
    at HTMLLIElement.TabView.element.ondragend (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/tabs/lib/tab-view.js:62:29)
```
To create the bug:

- Have a single pane with multiple tabs open
- Drag one to the right of the body of the editor (to split the window with the dragged tab on the right)

The error gets thrown the first time you do this

However, on subsequent occasions, the error does not get thrown, but the pane is not created and  the tab just <poof> ... disappears, gone. 

Packages:
```
MacOne:client work$ apm ls
Built-in Atom Packages (90)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.3
├── one-light-ui@1.10.3
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.6
├── archive-view@0.63.2
├── autocomplete-atom-api@0.10.1
├── autocomplete-css@0.16.1
├── autocomplete-html@0.7.3
├── autocomplete-plus@2.35.3
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.2
├── background-tips@0.27.0
├── bookmarks@0.44.3
├── bracket-matcher@0.85.5
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.3
├── exception-reporting@0.41.3
├── find-and-replace@0.207.6
├── fuzzy-finder@1.5.6
├── git-diff@1.3.5
├── go-to-line@0.32.0
├── grammar-selector@0.49.4
├── image-view@0.61.2
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.6.3
├── link@0.31.3
├── markdown-preview@0.159.11
├── metrics@1.2.3
├── notifications@0.67.1
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.249.4
├── snippets@1.1.4
├── spell-check@0.71.4
├── status-bar@1.8.7
├── styleguide@0.49.6
├── symbols-view@0.115.5
├── tabs@0.106.0
├── timecop@0.36.0
├── tree-view@0.217.0-7
├── update-package-dependencies@0.11.0
├── welcome@0.36.2
├── whitespace@0.36.2
├── wrap-guide@0.40.1
├── language-c@0.57.0
├── language-clojure@0.22.2
├── language-coffee-script@0.48.6
├── language-csharp@0.14.2
├── language-css@0.42.2
├── language-gfm@0.88.1
├── language-git@0.19.0
├── language-go@0.43.1
├── language-html@0.47.2
├── language-hyperlink@0.16.1
├── language-java@0.27.0
├── language-javascript@0.126.1
├── language-json@0.19.0
├── language-less@0.32.0
├── language-make@0.22.3
├── language-mustache@0.13.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.38.0
├── language-property-list@0.9.1
├── language-python@0.45.2
├── language-ruby@0.71.0
├── language-ruby-on-rails@0.25.2
├── language-sass@0.59.0
├── language-shellscript@0.25.0
├── language-source@0.9.0
├── language-sql@0.25.4
├── language-text@0.7.2
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.35.0
└── language-yaml@0.29.0

Community Packages (24) /Users/work/.atom/packages
├── Stylus@3.1.1
├── atom-beautify@0.30.2
├── auto-detect-indentation@1.3.0
├── auto-indent@0.5.0
├── busy-signal@1.4.3
├── editor-stats@0.17.0
├── file-icons@2.1.7
├── file-type-icons@1.3.4
├── intentions@1.1.2
├── jade-beautify@0.1.5
├── language-jade@0.7.2
├── language-nunjucks@4.1.0
├── language-pug@0.0.21
├── language-vue@0.23.0
├── linter@2.2.0
├── linter-eslint@8.2.1
├── linter-ui-default@1.6.1
├── pigments@0.39.1
├── predawn-syntax@1.0.4
├── project-manager@3.3.5
├── todo@0.6.0
├── tremendus-one-dark-ui@1.1.9
├── tremendus-predawn-light-syntax@1.0.4
└── unity-ui@2.1.11
```

**Comment by thodges314** [comment] 2017-08-11 17:45
Having the same issue.  I don't think I added or upgraded any packages since it last worked.

**Comment by kmcconnell** [comment] 2017-09-04 11:08
Issue still exists.

[Enter steps to reproduce:]

1. Open two files.
2. Right click one tab, click Split Left/Right.

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2


### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145

Error: Replacing non-existent child
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145:47)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:984:27)
    at Pane.module.exports.Pane.splitLeft (/Applications/Atom.app/Contents/Resources/app/src/pane.js:960:25)
    at TabBarView.module.exports.TabBarView.splitTab (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:379:37)
    at Object.TabBarView.addElementCommands.tabs:split-left (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:132:32)
    at HTMLUListElement.commandsWithPropagationStopped.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:83:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:38.8.0 application:reopen-project (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:04.4.0 tabs:split-left (div.title)
```

### Non-Core Packages

```

```

**Comment by QuintinS** [comment] 2017-09-21 19:47
Having the same issue. Same steps to reproduce as above.

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.107.1


### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145

Error: Replacing non-existent child
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:145:47)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:992:27)
    at Pane.module.exports.Pane.splitLeft (/Applications/Atom.app/Contents/Resources/app/src/pane.js:968:25)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/layout.js:48:33)
    at Object.end (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/layout.js:56:16)
    at HTMLLIElement.TabView.element.ondragend (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-view.js:62:29)
```

### Commands

```
  3x -3:08.3.0 core:backspace (input.hidden-input)
     -3:07.2.0 core:confirm (input.hidden-input)
     -3:05.7.0 core:select-all (input.hidden-input)
     -3:04.4.0 core:backspace (input.hidden-input)
     -3:01.7.0 core:move-left (input.hidden-input)
     -3:01.5.0 editor:newline (input.hidden-input)
     -2:58.5.0 core:save (input.hidden-input)
  2x -2:47.9.0 core:move-up (input.hidden-input)
     -2:47.5.0 core:move-right (input.hidden-input)
     -2:46.4.0 core:backspace (input.hidden-input)
     -2:45.3.0 core:save (input.hidden-input)
     -1:05.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -1:04.9.0 core:confirm (input.hidden-input)
     -0:55.1.0 command-palette:toggle (input.hidden-input)
     -0:54.2.0 editor:consolidate-selections (input.hidden-input)
     -0:54.2.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
emmet 2.4.3 
expand-region 0.3.2 
expand-selection-to-quotes 0.11.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.5 
jslint 1.5.1 
language-liquid 0.6.0 
linter 2.2.0 
linter-jshint 3.1.5 
linter-jsonlint 1.3.0 
linter-sass-lint 1.7.6 
linter-tidy 2.3.1 
linter-ui-default 1.6.8 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
multi-cursor 2.1.5 
Sass-Syntax-Highlight 0.1.1 
set-syntax 0.3.2 
split-diff 1.5.1 
word-jumper 0.3.0 
```
