### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Desktop\python projects\Mine\Category-Importation\...

### ISSUE THREAD

**Issue by PokestarFan** [atom/tabs#495] opened 2017-07-21 14:12 UTC
[Enter steps to reproduce:]

1. Try and open Readme.md

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Adding a pane item with URI 'C:\Users\~\Desktop\python projects\Mine\Category-Importation\README.md' that has already been destroyed

```
At C:\Users\~\AppData\Local\atom\app-1.18.0\resources\app\src\pane.js:493

Error: Adding a pane item with URI 'C:\Users\~\Desktop\python projects\Mine\Category-Importation\README.md' that has already been destroyed
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:493:21)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:468:20)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -1:04.4.0 tree-view:add-file (ol.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:00.6.0 core:confirm (input.hidden-input)
     -0:15.2.0 core:close (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-clock 0.1.13 
e-syntax 0.0.0 
er-syntax 0.0.0 
Hydrogen undefined 
my-theme-syntax 0.0.0 
pristine-ui 1.1.0 
pure-syntax 0.3.0 
zentabs 0.8.8 
```

**Comment by rsese** [comment] 2017-07-21 18:13
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates.  if you can consistently reproduce by just opening a particular README file and you can reproduce in safe mode (`atom --safe`), please let us know in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-21 18:13 UTC
