### ISSUE TITLE
Reverting ctrl-tab behavior appears to follow the order in which files are opened instead of visual tab order

### ISSUE THREAD

**Issue by mitchellnemitz** [atom/tabs#310] opened 2016-04-21 20:31 UTC
### Description

After updating to Atom 1.7.2 and reverting the `ctrl-tab` and `ctrl-shift-tab` behavior via the config in the release blog post:

```
'body':
  'ctrl-tab ^ctrl': 'unset!'
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab ^ctrl': 'unset!'
  'ctrl-shift-tab': 'pane:show-previous-item'
```

`ctrl-tab` and `ctrl-shift-tab` no longer tab through panes in order if they have been rearranged via drag-and-drop or if you are using the `Add New Tabs At End` config option from the `tabs` core package and open a file with an active tab somewhere in the middle of the list.

### Steps to Reproduce

1. Copy the config block from the MRU Tab Change blog post into your `keymap.cson` file.
1. Open 3-5 files from the tree / fuzzy open / however. Verify that you can `ctrl-tab` through them in order.
2. Drag-and-drop to rearrange them, or enable `Add New Tabs At End` in the `tabs` core package and select a tab other than the last, then open a file via the tree or the fuzzy finder.
3. Attempt to `ctrl-tab` and see that the order for selection is wrong.

**Expected behavior:** You can `ctrl-tab` through your open files in order as you could in Atom < 1.7.x releases.

**Actual behavior:** `ctrl-tab` does not progress through visual tab order and instead appears to follow the order of when the files were opened.

### Versions

```
$ atom --version
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by mitchellnemitz** [comment] 2016-04-21 20:32
This is partially addressed by https://github.com/atom/tabs/pull/302 but there still appears to be an issue with drag-and-drop.

**Comment by FGRibreau** [comment] 2016-04-22 18:52
Thank you for:

```
'body':
  'ctrl-tab ^ctrl': 'unset!'
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab ^ctrl': 'unset!'
  'ctrl-shift-tab': 'pane:show-previous-item'
```

I was wondering what was going on and your config make it work again :)

**Comment by mitchellnemitz** [comment] 2016-04-22 19:11
@FGRibreau you may also want to do an `apm install https://github.com/atom/tabs` to get the latest bugfixes for rearranging tabs, which solved half of my intial problem involving the `Add New Tabs At End` feature.

**Comment by amytruong** [comment] 2016-04-22 20:30
@lee-dohm was able to reproduce. 👍

**Comment by lee-dohm** [comment] 2016-04-22 21:44
@mitchellnemitz @FGRibreau please don't `apm install` built-in packages (it actually gives you a warning when you do so) because it can cause all kinds of mischief that is hard to track down. Built-in packages expect to be installed with specific versions of Atom. If you need newer versions of built-in packages, I would recommend using the Beta channel or building from source.

**Comment by aviau** [comment] 2016-05-10 20:09
I am getting the same issue in  1.7.3.

**Comment by doodhwala** [comment] 2016-09-12 17:23
I'm using Atom version 1.10.2 and modifying the keymap.cson worked for me.
Do confirm if the problem has been resolved and close this issue.

**Comment by johndanek** [comment] 2016-09-12 17:50
I've tried everything in this issue, and I still can't get ctrl+tab to behave as it does in Chrome/Safari. It works 50% of the time, but if I totally lift off the keyboard and try again, it starts going either backwards or in a different order.

**Comment by lee-dohm** [comment] 2016-09-13 02:37
@mitchellnemitz I can no longer reproduce this using Atom v1.10.2 on Mac OS X 10.11.6 given your (admittedly somewhat confusing repro steps). If you can still reproduce this bug, please post the exact steps you used to reproduce it.

**Comment by lee-dohm** [comment] 2016-09-13 02:39
@johndanek Have you followed the steps in the [Atom FAQ](https://discuss.atom.io/c/faq) here?

https://discuss.atom.io/t/i-want-ctrl-tab-to-work-like-it-used-to-how-do-i-do-that/28639

If so, please file a new Issue and fill out the template.

**Comment by Ben3eeE** [comment] 2016-09-13 05:00
>if they have been rearranged via drag-and-drop or if you are using the Add New Tabs At End config option from the tabs core package and open a file with an active tab somewhere in the middle of the list.

This sounds like what was fixed in https://github.com/atom/tabs/pull/302 and https://github.com/atom/tabs/pull/276.

**Comment by johndanek** [comment] 2016-09-13 20:05
@lee-dohm Uninstalling any tab-related packages and adding

    'body':
      'ctrl-tab ^ctrl': 'unset!'
      'ctrl-tab': 'pane:show-next-item'
      'ctrl-shift-tab ^ctrl': 'unset!'
      'ctrl-shift-tab': 'pane:show-previous-item'

to keymap.cson ended up with it working. Thanks!

**Comment by lee-dohm** [comment] 2016-09-14 00:03
Thanks @Ben3eeE. It sounds like this is fixed then. I'm going to go ahead and close it. Please let me know if I'm misunderstanding!

**Closed by lee-dohm** 2016-09-14 00:03 UTC
Labels: bug, more-information-needed
