### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by smdsbz** [atom/tabs#514] opened 2017-08-16 06:52 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught TypeError: Cannot read property 'firstChild' of undefined

```
At C:\Users\69406\AppData\Local\atom\app-1.19.1\resources\app\src\text-editor-component.js:2171

TypeError: Cannot read property 'firstChild' of undefined
    at TextEditorComponent.measureLongestLineWidth (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:2171:112)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:383:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:276:18)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:1430:18)
    at TextEditorComponent.didFocus (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:1454:35)
    at HTMLElement.addEventListener (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-element.js:36:67)
    at HTMLElement.PaneElement.activeItemChanged (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane-element.js:158:25)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.setActiveItem (~/AppData/Local/atom/app-1.19.1/resources/app/src/pane.js:337:28)
    at Pane.module.exports.Pane.activateItemAtIndex (~/AppData/Local/atom/app-1.19.1/resources/app/src/pane.js:475:25)
    at Pane.module.exports.Pane.activatePreviousItem (~/AppData/Local/atom/app-1.19.1/resources/app/src/pane.js:440:27)
    at Pane.module.exports.Pane.removeItem (~/AppData/Local/atom/app-1.19.1/resources/app/src/pane.js:630:22)
    at Pane.module.exports.Pane.destroyItem (~/AppData/Local/atom/app-1.19.1/resources/app/src/pane.js:706:22)
    at TabBarView.module.exports.TabBarView.onMouseDown (~/AppData/Local/atom/app-1.19.1/resources/app/node_modules/tabs/lib/tab-bar-view.js:709:25)
```

### Commands

```
     -0:29 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
activate-power-mode 2.2.0 
advanced-open-file 0.16.6 
atom-clock 0.1.13 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-terminal 0.8.0 
atom-ternjs 0.18.3 
autocomplete-python 1.10.0 
file-icons 2.1.10 
gcc-make-run 0.2.11 
gpp-compiler 3.0.7 
highlight-line 0.12.0 
highlight-selected 0.13.1 
indent-guide-improved 1.4.13 
language-cpp14 0.6.2 
markdown-pdf 1.5.4 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-pigments 0.2.2 
pdf-view 0.59.0 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
python-indent 1.1.0 
todo-show 1.11.0 
```

**Comment by rsese** [comment] 2017-08-16 17:46
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15311. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed** 2017-08-16 17:46 UTC
