### ISSUE TITLE
Tabs should close on middle click, not middle mousedown, like other tabbed applications.

### ISSUE THREAD

**Issue by collinstocks** [atom/tabs#198] opened 2015-07-27 12:43 UTC
In other applications that use tabs (such as Google Chrome, Firefox, etc), middle clicking tabs closes them. Atom sort of has this feature, but instead of closing the tab on mouseup (which triggers the click event), Atom closes the tab immediately upon mousedown. I was a bit surprised by this behavior, and more than once I've accidentally closed the wrong tab. In other applications where middle clicking a tab closes it, you can change your mind in the middle by dragging the cursor away from the tab while still holding down the middle button. This is the same behavior buttons have with respect to left clicking.

I think that tabs should be closed on middle click, rather than on middle mousedown.

I'm not sure what would go into changing this behavior, so I look forward to hearing feedback on this feature request.

**Comment by mnquintana** [comment] 2015-07-27 12:45
This was an intentional change added in https://github.com/atom/tabs/pull/124 – I'm not so sure that it should be reverted.

@atom/feedback

**Comment by collinstocks** [comment] 2015-07-27 12:47
@mnquintana #124 is about switching tabs. I'm talking about closing tabs.

**Comment by mnquintana** [comment] 2015-07-27 13:06
@collinstocks Ah sorry, my mistake. That would make this consistent with left clicking on the close icon.

**Comment by spaghetticodr** [comment] 2015-08-23 11:58
WTF, this is definately not a bug! Closing the tab immediately is standard and expected behaviour, at least in Windows (IE and anything that uses native Windows UI, Opera 12 also).

That's one of the reasons why I'm still using outdated Opera v12. Besides Firefox being slow and ugly as a snail, it's actually waits until you release the middle mouse button, making the UX even more slower.

Google Chrome and Firefox are both shitty examples on how UI should be implemented and the OS disrespected. What's next, you want supertitlebar that contains tabs instead on application title and controls, just because Chrome has it?

**Comment by jerone** [comment] 2015-08-29 10:17
:+1: In all tab-related programs I've used, closing a tab on middle click is executed on mouseup event, giving users a way to change their minds.

**Comment by jackjen** [comment] 2016-01-11 03:00
I personally find it very jarring to have the tab close on mouse down.
I'm going to list a few of the applications I use which are on mouse-up for closing tabs on Mac:

Safari: mouse up - check
Chrome: mouse up - check
Firefox: mouse up - check
Sublime Text 3: mouse up - check
Xcode 7: mouse up - check

Why would this be considered bad UX to have the action happen on click. To me it seems to be bucking the trend.

**Comment by savvopoulos** [comment] 2016-02-25 09:58
+1

**Closed** 2017-08-18 17:04 UTC
Labels: enhancement
