### ISSUE TITLE
Tabs remain marked as modified after switching branches

### ISSUE THREAD

**Issue by adamreisnz** [atom/tabs#428] opened 2017-03-30 20:16 UTC
@iolsen this is probably related to #306 

When I have some files open that exist in branch A but not in branch B, and then if I switch from A to B to check some code, all my open tabs are marked as modified, because the files no longer exist on the disk. This is correct, however, when I switch *back* to branch A, the tabs are all still marked as modified, and I have to "save" all the tabs, even though it's a no-op because nothing actually changed.

Any thoughts how we could address this?

**Comment by graygilmore** [comment] 2017-08-22 20:00
This also occurs when doing something like an interactive rebase.

**Comment by iolsen** [comment] 2017-08-22 20:49
I believe this is a duplicate of https://github.com/atom/atom/issues/14765, the fix for which will ship this week.

**Closed by iolsen** 2017-08-22 20:49 UTC
Labels: bug
