### ISSUE TITLE
Uncaught Error: Setting active pane that is not present in pane container

### ISSUE THREAD

**Issue by ReactiveSainz** [atom/tabs#476] opened 2017-07-04 04:52 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At C:\Users\nigth\AppData\Local\atom\app-1.18.0\resources\app\src\pane-container.js:253

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane-container.js:253:21)
    at Pane.module.exports.Pane.activate (~/AppData/Local/atom/app-1.18.0/resources/app/src/pane.js:875:20)
    at Immediate.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:704:39)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -5:45 autocomplete-plus:confirm (input.hidden-input)
  3x -5:43.2.0 core:move-right (input.hidden-input)
     -5:33.2.0 intentions:highlight (input.hidden-input)
     -5:33 core:save (input.hidden-input)
     -5:14.3.0 editor:newline (input.hidden-input)
     -5:13 autocomplete-plus:confirm (input.hidden-input)
  3x -5:08.7.0 core:backspace (input.hidden-input)
     -5:06.4.0 autocomplete-plus:confirm (input.hidden-input)
  2x -5:04.8.0 core:move-right (input.hidden-input)
  2x -5:00.0 core:backspace (input.hidden-input)
     -4:52.1.0 core:move-right (input.hidden-input)
     -4:51 intentions:highlight (input.hidden-input)
     -4:50.7.0 core:save (input.hidden-input)
  2x -4:19.4.0 pane:close (div.item-views)
     -3:30.1.0 settings-view:open (textarea.)
  2x -0:24.4.0 tree-view:toggle (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.30.3 
atom-clock 0.1.12 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.4 
atom-mocha 0.0.12 
autocomplete-haskell 0.7.2 
autocomplete-json 5.5.0 
autocomplete-modules 1.6.10 
autocomplete-python 1.9.1 
babel-react-syntax 1.2.0 
busy-signal 1.4.3 
color-picker 2.2.5 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.8 
flex-tool-bar 0.12.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
html-to-css 0.2.2 
imdone-atom 2.2.6 
imdone-atom-github 0.1.11 
intentions 1.1.2 
language-babel 2.66.0 
linter 2.2.0 
linter-csslint 1.3.4 
linter-eslint 8.2.1 
linter-pycodestyle 2.0.2 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.2 
linter-write-good 0.9.0 
oceanic-next 1.0.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
pure-syntax 0.2.1 
script 3.15.0 
todo 0.6.0 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tool-bar-atom 1.7.0 
tool-bar-main 0.0.10 
tree-view-git-status 1.4.0 
```

**Comment by rsese** [comment] 2017-07-06 00:38
Thanks for the report!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14716. You may want to subscribe there for updates and if the error is reproducible and reproducible in safe mode (`atom --safe`), please let us know in that issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-06 00:38 UTC
