### ISSUE TITLE
Moving Tabs - Random Drop

### ISSUE THREAD

**Issue by Wade-BuildOtto** [atom/tabs#326] opened 2016-05-17 22:01 UTC
Whenever I move a tab it moves other tabs around into some random location. 

I am trying to keep my js and html tabs close together but its a mess, 

also if the preview mode can have a disable option, I prefer the original one click open

**Comment by Ben3eeE** [comment] 2016-05-19 12:28
Do you have the "add new tabs at end" option checked? This might be a duplicate of https://github.com/atom/tabs/issues/293.

If it is not a duplicate: Are you using the latest version of Atom? Can you reproduce the problem in safe mode? To start Atom in safe mode quit all instances of Atom and run `atom --safe`. Are you using the mouse click and drag to rearrange the tabs?

You can get the original one click open with the `single-click-open` package: https://atom.io/packages/single-click-open

**Comment by Wade-BuildOtto** [comment] 2016-05-19 16:15
disabling the add new tabs at end fixed the moving tab issue.

thx.

**Comment by Ben3eeE** [comment] 2016-05-19 20:36
Great.
@50Wliu Close?

**Comment by 50Wliu** [comment] 2016-05-19 21:06
No, since "Add New Tabs at End" is a configuration option provided by Tabs, we should support it correctly.  @anderoonies has this been fixed in master already?

**Comment by antoinebeaumont** [comment] 2016-05-23 08:49
Atom : 1.7.3
_"Move New Tab At End"_ : ON
Layout : 2 columns

When I move a tab from both columns, a random tab is moved, not the one I selected

No problem with _"Move New Tab At End"_ : OFF

**Comment by Ben3eeE** [comment] 2016-05-23 09:13
Atom 1.7.4 updated the tabs package which fixed this behavior for me. Can you reproduce it in Atom 1.7.4?

**Comment by antoinebeaumont** [comment] 2016-05-23 09:21
@Ben3eeE works great, thank you!

**Comment by 50Wliu** [comment] 2016-05-23 16:10
Thanks for the update @antoinebeaumont!

**Closed by 50Wliu** 2016-05-23 16:10 UTC
Labels: bug

**Comment by Ben3eeE** [comment] 2016-05-24 12:05
This is not entirely fixed actually.
If you move a tab to another pane it will be dropped at the end rather than at the location where it was dropped with the Add the new tabs at end configuration option.

**Comment by 50Wliu** [comment] 2016-05-24 12:10
That seems like a different (albeit related) issue.

**Comment by Ben3eeE** [comment] 2016-05-24 12:21
Alright.
I can open a new issue describing everything later today.
