### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dataTransfer' of null

### ISSUE THREAD

**Issue by tsbarnes** [atom/tabs#203] opened 2015-08-26 00:49 UTC
Any time I close the last tab after installing the [todo-manager](https://github.com/benjaminRomano/todo-manager) package, this error occurs.  Obviously, I'll submit an issue on that package as well, but if nothing else this package should probably handle this error more gracefully.

**Atom Version**: 1.0.7
**System**: Ubuntu 15.04
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.82.0

### Stack Trace

Uncaught TypeError: Cannot read property 'dataTransfer' of null

```
At /opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:518

TypeError: Cannot read property 'dataTransfer' of null
  at TabBarView.module.exports.TabBarView.onDragStart (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:518:26)
  at tabs-tab.<anonymous> (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.$event.dispatch (/home/scott/.atom/packages/todo-manager/node_modules/atom-bottom-dock/node_modules/slickgrid/lib/jquery.event.drag-2.2.js:374:19)
  at space-pen-ul.<anonymous> (/home/scott/.atom/packages/todo-manager/node_modules/atom-bottom-dock/node_modules/slickgrid/lib/jquery.event.drag-2.2.js:259:40)
  at Function.jQuery.extend.each (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:374:23)
  at [object Object].jQuery.fn.jQuery.each (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:139:17)
  at Object.$special.drag.hijack (/home/scott/.atom/packages/todo-manager/node_modules/atom-bottom-dock/node_modules/slickgrid/lib/jquery.event.drag-2.2.js:253:44)
  at HTMLDocument.$special.drag.handler (/home/scott/.atom/packages/todo-manager/node_modules/atom-bottom-dock/node_modules/slickgrid/lib/jquery.event.drag-2.2.js:185:10)
  at HTMLDocument.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDocument.$event.dispatch (/home/scott/.atom/packages/todo-manager/node_modules/atom-bottom-dock/node_modules/slickgrid/lib/jquery.event.drag-2.2.js:374:19)
  at HTMLDocument.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/home/scott/Documents/Code",
    "disabledPackages": [
      "language-ruby"
    ],
    "themes": [
      "metro-ui",
      "ax-monokai-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.0
autocomplete-php, v0.3.7
autocomplete-python, v0.5.3
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
ax-monokai-syntax, v0.1.0
bottom-dock, v0.3.2
browser-refresh, v0.9.0
color-picker, v2.0.11
django-templates, v0.5.0
file-icon-supplement, v0.8.3
file-icons, v1.6.9
flex-tool-bar, v0.5.0
git-tab-status, v1.9.2
grunt-runner, v0.11.0
language-apache, v1.3.0
language-autotools, v2.0.0
language-cmake, v0.1.4
language-conky, v0.2.0
language-cpp14, v0.4.0
language-dart, v0.2.0
language-diff, v0.3.1
language-dotenv, v1.0.0
language-gettext, v0.6.1
language-gitignore, v0.2.0
language-haml, v0.21.0
language-htaccess, v0.1.1
language-ini, v1.11.0
language-log, v0.6.0
language-lua, v0.9.4
language-ppd, v0.3.1
language-qml, v1.0.0
language-rspec, v0.3.0
language-ruby-without-erb, v0.52.0
language-svg, v0.8.0
linter, v1.4.3
linter-bootlint, v0.0.6
linter-coffeelint, v1.0.2
linter-cpplint, v0.1.4
linter-csslint, v1.0.5
linter-erb, v0.1.1
linter-haml, v1.0.0
linter-js-yaml, v1.1.1
linter-jshint, v1.1.5
linter-less, v2.1.0
linter-lua, v1.0.0
linter-pep8, v1.0.1
linter-ruby, v1.0.2
linter-scss-lint, v2.0.0
linter-shellcheck, v1.0.1
linter-xmllint, v0.0.7
metro-ui, v2.2.2
minimap, v4.13.1
minimap-git-diff, v4.1.8
pigments, v0.11.0
recent-projects, v0.8.6
tabs-to-spaces, v0.11.1
todo-manager, v0.2.2
tool-bar, v0.1.8
travis-ci-status, v0.16.0
tree-view-git-status, v0.1.2

# Dev
No dev packages
```

**Comment by mariosergiomachado** [comment] 2015-08-27 22:51
Here is not when I close the last tab.

**Comment by p-ho** [comment] 2015-09-07 20:24
I can confirm the relation between todo-manager and this issue. As soon as I've uninstalled todo-manager, the issue was resolved.

Furthermore I've experienced that it isn't possible to drag and drop tabs (aka change the order of tabs) having todo-manager installed.

**Comment by benjaminRomano** [comment] 2015-09-07 20:47
@p-ho could you copy and paste the error message you get into this [issue](https://github.com/benjaminRomano/todo-manager/issues/9). I'll take a look and see if I can figure out what's causing this issue.

**Comment by Ben3eeE** [comment] 2016-10-11 11:23
Closing since this was an error in the `todo-manager` package that has been fixed already.

**Closed by Ben3eeE** 2016-10-11 11:23 UTC
Labels: uncaught-exception
