### ISSUE TITLE
Unexpected token .

### ISSUE THREAD

**Issue by erickmerchant** [atom/tabs#127] opened 2015-04-01 22:52 UTC
Uncaught Error: /Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:1(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT                                                              ^Unexpected token ./Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:1(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT                                                              ^SyntaxError: Unexpected token .    at exports.runInThisContext (vm.js:75:16)    at Module._compile (module.js:458:25)    at Object.Module._extensions..js (module.js:493:10)    at Module.load (module.js:370:32)    at Function.Module._load (module.js:325:12)    at Module.require (module.js:380:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:128:79)    at EventEmitter.emit (events.js:119:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:99:23)    at EventEmitter.emit (events.js:119:17)

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.67.0

### Stack Trace

Uncaught Error: /Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:1
(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT
                                                              ^
Unexpected token .
/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:1
(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT
                                                              ^
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:458:25)
    at Object.Module._extensions..js (module.js:493:10)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)

```
At /Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:77

Error: /Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:1
(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT
                                                              ^
Unexpected token .
/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:1
(function (exports, require, module, __filename, __dirname) { .exports.DEFAULT
                                                              ^
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:458:25)
    at Object.Module._extensions..js (module.js:493:10)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)
  at metaToValue (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:77:15)
  at Object.exports.require (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:157:34)
  at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom.js:711:23)
  at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:519:21)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:472:18)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:179:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -4:24.0 application:new-file (atom-text-editor.editor)
     -4:23.0 core:paste (atom-text-editor.editor)
     -4:21.8 command-palette:toggle (atom-text-editor.editor)
     -4:19.6 core:confirm (atom-text-editor.editor.mini)
     -4:19.5 atom-html-preview:toggle (atom-text-editor.editor)
     -3:59.9 find-and-replace:show (atom-text-editor.editor)
  3x -3:58.9 core:confirm (atom-text-editor.editor.mini)
     -3:46.7 find-and-replace:show (atom-text-editor.editor)
 30x -3:44.7 core:confirm (atom-text-editor.editor.mini)
     -0:11.5 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "atom-html-preview"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.5.0
file-types, v0.3.0
language-apache, v1.2.0
language-expressionengine, v0.2.3
monokai, v0.13.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-04-28 20:50
I believe this is a duplicate of https://github.com/atom/atom/issues/6276 please subscribe to that issue for updates.

**Closed by kevinsawicki** 2015-04-28 20:50 UTC
